### ISSUE TITLE
How to achieve API basic auth with docker container?

### ISSUE THREAD

**Issue by ghost** [Landoop/kafka-topics-ui#103]
^

**Comment by andmarios** [comment]
For this image (but not the rest of our UIs for now), you can add something like this to your *docker run*:

    -e "CADDY_OPTIONS=basicauth / [USER] [PASS]"

Please remember though, generally it is a bad idea to use basic authentication without SSL.

**Comment by andmarios** [comment]
I don't see a follow up, so I gather the issue was solved. Feel free to re-open if the above doesn't work for you.
