### ISSUE TITLE
topic not displayed as avro

### ISSUE THREAD

**Issue by eimarfandino** [Landoop/kafka-topics-ui#105]
Hi, 

I sent an avro message to the kafka bus but when going to the landoop topics ui the topic type is still "..." instead of AVRO. 

I can see the kafka rest is able to communicate with the schema registry. 
Any ideas?

**Comment by Antwnis** [comment]
When you say `Avro message` do you mean "A message with Avro in the KEY and Avro in the VALUE as well" ? To my knowledge Kafka REST cannot consumer messages with mixed-content ( i.e. String KEY + Avro VALUE)

**Comment by jglambed** [comment]
Also, it may be shown as "..." in the list if there is no schema for the topic, but display it in `tree` or `grid` view if the messages are actually AVRO

**Comment by eimarfandino** [comment]
ok, letme clarify this. I sent a message to the bus, a topic called "twitter". The message schema looks like this:
```
{
  "type": "record",
  "name": "twitter_schema",
  "namespace": "com.miguno.avro",
  "fields": [
    {
      "name": "username",
      "type": "string",
      "doc": "Name of the user account on Twitter.com"
    },
    {
      "name": "tweet",
      "type": "string",
      "doc": "The content of the user's Twitter message"
    },
    {
      "name": "timestamp",
      "type": "long",
      "doc": "Unix epoch time in seconds"
    }
  ],
  "doc:": "A basic schema for storing Twitter messages"
}
```

the message sent looks like this:

```
{
  "username": "miguno",
  "tweet": "Rock: Nerf paper, scissors is fine.",
  "timestamp": 1366150681
}
```

I see in the topics UI shows like this with "...". I am expecting AVRO. 
![screen shot 2018-03-09 at 09 56 34](https://user-images.githubusercontent.com/3019114/37198916-2f2832de-2380-11e8-96d9-d24171889db8.png)

Do you know why is this happening?

**Comment by jglambed** [comment]
This is the schema of the topic value, and indeed it is an AVRO schema.
But what about the topic key?
You can check this example:
http://kafka-topics-ui.landoop.com/#/cluster/UAT/topic/n/nyc_yellow_taxi_trip_data/ - Topic data
http://schema-registry-ui.landoop.com/#/cluster/UAT/schema/nyc_yellow_taxi_trip_data-value/version/1 Topic value schema.

As there is not schema for the KEY we cant say such a thing as `The topic is AVRO` 

Even that in the end, we use AVRO deserializer to consume the data

**Comment by eimarfandino** [comment]
@jglambed so if i define a topic key it works?

I sent a topic key and still displaying "..."

this is the raw data:
```
[
  {
    "topic": "mytopic",
    "key": "mytopickey",
    "value": "\u0000\u0000\u0000\u0000\u0001\fmigunoFRock: Nerf paper, scissors is fine.²¸î\n",
    "partition": 0,
    "offset": 0
  }
]
```

here an example where the key is null and the topic is displayed as AVRO. why is that? Seems so random.  
![kafka topics ui browse kafka data 1](https://user-images.githubusercontent.com/3019114/37216950-871a5ae4-23bc-11e8-9e6c-3dc7120789a4.png)

**Comment by eimarfandino** [comment]
so, how does the UI defines if it is AVRO or not? It seems pretty random

**Comment by Antwnis** [comment]
@eimarfandino It requires a schema to exist for **both**  the key and the value

So if your topic is called `topicA` you should have two subjects/schemas registered in the schema-registry:
- topicA-key
- topicA-value

The backend (kafka-rest) cannot deserialize mixed-content topics. It requires **both** the key and the value to be of avro type - in order for the avro deserializer to be applied

I trust the above clarifies your question. If not please re-open this ticket

**Comment by irbian** [comment]
Related https://github.com/confluentinc/kafka-rest/issues/210
