### ISSUE TITLE
Embedded type schema avro messages are not deserialized

### ISSUE THREAD

**Issue by svkx** [Landoop/kafka-topics-ui#108]
Hi,

I have a problem with avro schema loaded as union in KafkaProducer, which eventually represents the schema with embedded type in schema-registry. Kafka-topics-ui is not able to deserialize them, though it identifies the topic as avro type, but data type as binary.
I simplified the schema from my case, but the test schema to reproduce the issue may look like this. The event is a Record with an array of SubRecords
[
  {
    "namespace": "test",
    "name": "SubRecord",
    "type": "record",
    "fields": [
      { "name": "id", "type": "int" }
    ]
  },
  {
    "namespace": "test",
    "name": "Record",
    "type": "record",
    "fields": [
      { "name": "name", "type": "string" },
      { "name": "subrecords", "type": { "type": "array", "items": "SubRecord" } }
    ]
  }
]

Both key and value are serialized with KafkaAvroSerializer

**Comment by lazy8** [comment]
Hi,

I think I've run into the same problem. 
I am using the docker image: `landoop/fast-data-dev:1.0.1`

My avro schema contains the following field:
```
{
      "name": "unit",
      "type": {
        "type": "enum",
        "name": "TemperatureUnit",
        "doc": "supported temperature units",
        "symbols": [
          "C",
          "F",
          "K"
        ]
      }
    }
```

Is there any fix or workaround for this?

**Comment by svkx** [comment]
@lazy8 thank you for commenting out, I didn't hear back on that issue for a while. Unfortunately, I am not able to find any workaround, so I use avro console consumer by confluent for now.

**Comment by andmarios** [comment]
Hi @ssbiox. I think the issue lies in that you define your schema using multiple schemas, whilst schema registry expects one schema which embeds all children schemas.

As an example, your schema:
```
[
  {
    "namespace": "test",
    "name": "SubRecord",
    "type": "record",
    "fields": [
      { "name": "id", "type": "int" }
    ]
  },
  {
    "namespace": "test",
    "name": "Record",
    "type": "record",
    "fields": [
      { "name": "name", "type": "string" },
      { "name": "subrecords", "type": { "type": "array", "items": "SubRecord" } }
    ]
  }
]
```
Can be translated like this:
```
{
  "type": "record",
  "name": "Record",
  "namespace": "test",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "subrecords",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "SubRecord",
          "fields": [
            {
              "name": "id",
              "type": "int"
            }
          ]
        }
      }
    }
  ]
}
```
This version should  be accepted by both Schema Registry and Schema Registry UI.

**Comment by svkx** [comment]
@andmarios, Schema Registry accepts this schema and shows as a unified one, also if I use avro-tools it is also accepted by Schema Registry. All Java serializers/deserializer are working fine with that, but *only* kafka-topic-ui is not able to deserialize events with schemas where one record holds another subrecord.

I'm not reporting a problem with Schema Registry or Schema Registry UI. It is a problem of Kafka Topics UI.

**Comment by stheppi** [comment]
@ssbiox
  Kafka-Topics-Ui uses the Rest-proxy it doesn't do any deserialization on it's own as you might know already. 
  What does the Rest-Proxy logs say? 

@lazy8,
  Your schema is not related to nested schemas. However you should look at the Rest-Proxy logs and see what it says.

**Comment by andmarios** [comment]
@ssbiox, Kafka Topics UI works with subrecords. Here is how you can test it yourself with fast-data-dev (kafka docker):

In one terminal, start fast-data-dev:

```
docker run --rm -it -p 3030:3030 --name fdd landoop/fast-data-dev
```

Open a second terminal, connect to the container so you can use the kafka cli apps, create the schema you gave as an example and produce some data:

```
docker exec -it fdd bash
cat <<EOF > avro-schema.json
{
  "type": "record",
  "name": "Record",
  "namespace": "test",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "subrecords",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "SubRecord",
          "fields": [
            {
              "name": "id",
              "type": "int"
            }
          ]
        }
      }
    }
  ]
}
EOF
kafka-topics --zookeeper localhost:2181 --create --topic avro-subrecords --partitions 3 --replication-factor 1
echo '{"name":"ssbiox","subrecords":[{"id":1},{"id":2}]}' \
| kafka-avro-console-producer --broker-list localhost:9092 --topic avro-subrecords --property value.schema="$(cat /avro-schema.json)" --property http://localhost:8081
```
At last open `http://localhost:3030` to verify that your entry shows correctly in Kafka Topics UI:
![screenshot_20180507_134559](https://user-images.githubusercontent.com/1239679/39698499-b63132a2-51fd-11e8-80d9-74fd1ad83baf.png)

Also I am
 surprised that you say your schema works with Schema Registry. Up to Schema Registry 4.0.1 (at least, I didn't try with 4.1.0) such schemas are not supported and you get this error instead from kafka-avro-console-producer: `org.apache.avro.AvroTypeException: Unknown union branch name`.

**Comment by svkx** [comment]
@andmarios 
I use another docker image landoop/kafka-topics-ui instead of landoop/fast-data-dev - is it the same product/version?

@stheppi 
Thank you, I didn't realize that, it's needed to verify rest-proxy logs.

**Comment by andmarios** [comment]
@ssbiox landoop/fast-data-dev is a docker image that contains kafka, schema registry, connect, Landoop UIs, has bash completion for kafka command line apps etc. I suggested it because it is easy to test things without affecting your main kafka setup.  :)

https://github.com/Landoop/fast-data-dev

**Comment by lazy8** [comment]
@stheppi Thanks for answering. You are right, my problems went away after a clean restart. It was just some caching problem during development.
