### ISSUE TITLE
Sometimes on new consumer groups, first consumers don't show any messages

### ISSUE THREAD

**Issue by imdark** [Landoop/kafka-topics-ui#11]
if a a consumer group by a name is created for the first time, it might take rest-proxy take a few milliseconds to pull its messages, since kafka-topics-ui immediately kills new consumers, it might never get a chance to access the messages on the topic.

To repro, 
1. create a new topic in kafka 
2.publish json or binary messages to the new topic (avro-schema adds a timeout that stop you from reproducing)
3.only access it by kafka-topics-ui, the messages will probably not appear in ui and will never be pulled since rest proxy will not get a chance to populate the consumer.

**Comment by Antwnis** [comment]
It's been a while - and tried to re-produce it on the latest version `0.9.2` of *topics-ui*
It seems to be working ok now, so closing this issue

**Comment by fuyar** [comment]
I think that #74 is related, first getRecord is reallllllly slow with the new consumer (~ 5sec in my case).

**Comment by jglambed** [comment]
You can change the `POLL_TIMEOUT` to a smaller amount of seconds to make it faster, but this may cause no data issues in certain topics. Unfortunately this is how Kafka Rest works.
We have solved those issues in [Lenses.io](https://lenses.io/solutions/usecases/lenses-for-data-platform/)
