### ISSUE TITLE
serve with <base> (non root web path)

### ISSUE THREAD

**Issue by adamdecaf** [Landoop/kafka-topics-ui#111]
I'm trying to serve kafka-topics-ui off a path (`/kafka-topics-ui`). This works for the html assets, but not for the `/api/...` routes. They 404 (`<base>` isn't used for absolute urls).

I tried editing [`env.js` to use a relative api path](https://github.com/Landoop/kafka-topics-ui/blob/master/env.js#L5), but that gets [overridden in the dockerfile](https://github.com/Landoop/kafka-topics-ui/blob/v0.9.3/docker/run.sh#L26-L30). 

In that dockerfile I found `EXPERIMENTAL_PROXY_URL`, which solves my problem. Reading the commit (https://github.com/Landoop/kafka-topics-ui/commit/9d1591d53162bf0c0317bf5e9c8c0ddd5860625e) for that env var though makes me think it won't stick around. 

I am running kafka-topics-ui in kubernetes though, but the issue of `<base>` would apply outside k8s.

**Comment by jglambed** [comment]
Not supported
