### ISSUE TITLE
error_code":40403,"message":"Consumer instance not

### ISSUE THREAD

**Issue by buntydevops** [Landoop/kafka-topics-ui#112]
We are seeing strange issue with Topic UI

When loading topic message we see errors like

####################
HTTP ERROR:  Failed at method [POST] [/api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-23-02-076/instances/kafka-topics-ui-binary/assignments] with error: 
{"data":{"error_code":40403,"message":"Consumer instance not found."},"status":404,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-23-02-076/instances/kafka-topics-ui-binary/assignments","data":{"partitions":[{"topic":"integration_scheduledrefill","partition":2},{"topic":"integration_scheduledrefill","partition":1},{"topic":"integration_scheduledrefill","partition":0}]},"dataType":"json","headers":{"Content-Type":"application/vnd.kafka.v2+json","Accept":""}},"statusText":"Not Found"} 
DATA SENT: 
Object { partitions: […] }

However when refreshing 4-5 time or more it renders the content fine.

integration_scheduledrefill Starting [ViewTopicCtrl]
angular.js:14525:17
integration_scheduledrefill DETECTING TYPE.. HAVE CONSUMED THIS TOPIC BEFORE, IT'S IN COOKIE. TYPE IS [binary]
angular.js:14525:17
... DATA FOR PARTITION [ ALL ]...
angular.js:14525:17
integration_scheduledrefill CREATING CONSUMER:  
Object { group: "kafka_topics_ui_binary_2018-04-19-01-28-31-742", instance: "kafka-topics-ui-binary" }
 2018-04-19-01-28-31-742
angular.js:14525:17
HttpFactory:  curl -X POST -H "Content-Type: application/vnd.kafka.v2+json --data {"name": "kafka-topics-ui-binary", "format": "binary", "auto.offset.reset": "earliest", "auto.commit.enable": "false"} /api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-28-31-742
angular.js:14525:17
integration_scheduledrefill POLL STEPS START
angular.js:14525:17
HttpFactory:  curl -X GET -H "Content-Type:  --data  /api/kafka-rest-proxy/topics/integration_scheduledrefill/partitions
angular.js:14525:17
integration_scheduledrefill 1) DONE: GOT ALL PARTITIONS 
Object { data: […], status: 200, headers: wd(), config: {…}, statusText: "OK" }
angular.js:14525:17
integration_scheduledrefill 2) ACTUAL PARTITIONS TO ASSIGN 
Object { partitions: […] }
angular.js:14525:17
HttpFactory:  curl -X POST -H "Content-Type: application/vnd.kafka.v2+json --data {"partitions":[{"topic":"integration_scheduledrefill","partition":2},{"topic":"integration_scheduledrefill","partition":1},{"topic":"integration_scheduledrefill","partition":0}]} /api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-28-31-742/instances/kafka-topics-ui-binary/assignments
angular.js:14525:17
integration_scheduledrefill 3) DONE: ASSIGNED PARTITIONS TO CONSUMER
angular.js:14525:17
HttpFactory:  curl -X POST -H "Content-Type: application/vnd.kafka.v2+json --data {"partitions":[{"topic":"integration_scheduledrefill","partition":2},{"topic":"integration_scheduledrefill","partition":1},{"topic":"integration_scheduledrefill","partition":0}]} /api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-28-31-742/instances/kafka-topics-ui-binary/positions/beginning
angular.js:14525:17
integration_scheduledrefill 4) SEEK TO BEGGINING FOR ALL PARTITIONS DONE
angular.js:14525:17
integration_scheduledrefill 5) START POLLING WITH CONSUMER: 
Object { group: "kafka_topics_ui_binary_2018-04-19-01-28-31-742", instance: "kafka-topics-ui-binary" }
angular.js:14525:17
HttpFactory:  curl -X GET -H "Content-Type: application/vnd.kafka.v2+json --data  /api/kafka-rest-proxy/consumers/kafka_topics_ui_binary_2018-04-19-01-28-31-742/instances/kafka-topics-ui-binary/records?timeout=5000&max_bytes=500000
angular.js:14525:17
integration_scheduledrefill 6) DONE: GOT RECORDS 189 
Object { data: […], status: 200, headers: wd(), config: {…}, statusText: "OK" }
angular.js:14525:17
integration_scheduledrefill 7) SAVING TYPE TO COOKIE binary
angular.js:14525:17
integration_scheduledrefill GOT DATA, WILL RENDER  [ 189 ] [ binary ] MESSAGES
angular.js:14525:17
integration_scheduledrefill 8) CONSUMER DELETED 
Object { group: "kafka_topics_ui_binary_2018-04-19-01-28-31-742", instance: "kafka-topics-ui-binary" }

Is this a know issue. We have setup Rest Proxy behind a loadbalancer.

**Comment by ambhojgoyal** [comment]
@buntydevops This issue is already addressed. even i faced the same issue and my setup is exactly similar to yours (Rest proxy behind load balancer). They have also explained why this behavior is there. You can tune the timeout value acordingly.
[here](https://github.com/confluentinc/kafka-rest/issues/211)

**Comment by buntydevops** [comment]
Hi @ambhojgoyal  Even I tried testing with Postman and see the same issue in our loadbalancer (Azure L4) we have specified a timeout of 15 minutes and the Kafka Rest has default

**Comment by jglambed** [comment]
This does not look like a Kafka Topics UI issue, more like a loadbalancer (Azure) issue.
Hopefully you have already sorted out, if not feel free to ping us again and we ll check it again.
