### ISSUE TITLE
Versions compatibility

### ISSUE THREAD

**Issue by onzo-mateuszzakarczemny** [Landoop/kafka-topics-ui#113]
I've deployed kafka-topcis-ui, kafka-rest and schema-registyr on kubernetess with following versions:
confluentinc/cp-schema-registry:3.3.1
confluentinc/cp-kafka-rest:3.3.1
landoop/kafka-topics-ui:0.9.3

My topcis are in json format but messages list in kafka-topics-ui is seems to be in binary format.
What's more interesting when I change all above versions to `latest` I don't get any messages from kafka-topics-ui. Is the most recet kafka-topics-ui compatibile with lastest kafka-rest?

**Comment by andmarios** [comment]
Hi @onzo-mateuszzakarczemny. The latest version of Kafka Topics UI (0.9.3) should work throughout REST Proxy versions 3.2 to 4.1 (the latest).

For the message encoding detection, we rely on REST Proxy. It has some limitations that you may hit. First the key and value need to have the same encoding or else the key should be null. Another issue could come from the fact that we start reading from the first message. If your first message (or any other) isn't in JSON, it could throw REST Proxy's encoding detection off.

**Comment by onzo-mateuszzakarczemny** [comment]
@andmarios thanks, you helped me a lot. It seems that I'm getting binary format because my key is just a string, not proper json. Anyway, it's very strange latest versions are not working.
The format detection logic is part of kafka-rest? Maybe this should be configurable in kafka-topics-ui? I could raise a PR for that. `env.js` is the right place to contain such config?

**Comment by andmarios** [comment]
Although I am not very familiar with this part of the code, I believe what we do is that we ask REST Proxy to try to decode a topic with all available options —it only supports three: binary, avro and json. We give priority to the avro and json over binary. So if we don't return json, it means REST Proxy does not recognize your topic as such and there isn't anything you can do to change that.

If you wanna have a look at it, I would suggest to start from the rest proxy api to check if it can decode your topic.

**Comment by onzo-mateuszzakarczemny** [comment]
@andmarios Thanks. I will close that issue.
