### ISSUE TITLE
Invalid docker tags

### ISSUE THREAD

**Issue by onzo-mateuszzakarczemny** [Landoop/kafka-topics-ui#114]
According to https://hub.docker.com/r/landoop/kafka-topics-ui/tags/
the latest tags was generated 3 months ago and size is 10 Mb. However, the last version was generated 7 months ago and it's size is 9 MB.
I think the last version tag is missing.

**Comment by jglambed** [comment]
Latest tag in docker is 0.9.4 which is our latest release as well.
