### ISSUE TITLE
Data type: binary for some topics

### ISSUE THREAD

**Issue by hectorgarzon** [Landoop/kafka-topics-ui#120]
Hi,
I would like to know why a topic is marked as "Data type: binary" on DATA tab although it has AVRO format.
For example, this topic on your live demo: http://kafka-topics-ui.landoop.com/#/cluster/UAT/topic/n/sea_vessel_reports_roundtrip/ 

This one has also AVRO format and it is marked as "Data type: avro": http://kafka-topics-ui.landoop.com/#/cluster/UAT/topic/n/reddit_posts/
Both have defined schemas for key and value.
- http://schema-registry-ui.landoop.com/#/cluster/UAT/schema/sea_vessel_reports_roundtrip-value/version/1
- http://schema-registry-ui.landoop.com/#/cluster/UAT/schema/sea_vessel_reports_roundtrip-key/version/1

Items on that "binary" topics are not well formated on topics-ui

Does it depend on the way the producer has created first item?

Thanks

**Comment by Antwnis** [comment]
@hectorgarzon have a look at https://lenses.stream

The open-source backend service of the topics-ui is quite limited, however the LENSES backend can deserialize all messages, even from topics with mixed-content ( i.e. LONG / AVRO )

**Comment by andmarios** [comment]
We rely on Kafka REST to do the detection. One requisite is that the key has the same encoding as the value, or it is null. Even one message in the topic that doesn't conform to this, can throw Kafka REST's detection off.

About the second topic you mention (sea_vessel_reports_roundtrip) it is actually AVRO. It's just that the content is binary, encapsulated in AVRO.

**Comment by hectorgarzon** [comment]
Thanks for your help

I've just produced some items from java code using io.confluent.kafka.serializers.KafkaAvroSerializer on both key and value and it is saying the same: format avro but Data type: binary.
I'm using KafkaTemplate's send method to send a GenericRecord (generated from right schema) to that topic.

Same happens with schema-registry's kafka-avro-console-producer

Do you know if there is a parameter to determine not to send it as binary? Or if it's because I'm using a GenericRecord instead of a Specific class?

**Comment by hectorgarzon** [comment]
I've made this test: on a new topic I've produced a record using REST API 3.2.2 (https://docs.confluent.io/3.2.2/kafka-rest/docs/api.html#overview) with this sentence:
```
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v2+json" -H "Accept: application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json" http://deheremap7373:8082/topics/avrotest2 --data '{"value_schema": "{\"type\": \"record\", \"name\": \"schemaavro\", \"fields\": [{\"name\":\"f1\",\"type\": \"string\"},{\"name\":\"f2\",\"type\": \"string\"},{\"name\":\"f3\",\"type\": \"string\"},{\"name\":\"f4\",\"type\": \"string\"},{\"name\":\"f5\",\"type\": \"string\"}]}", "records":[{"value":{"f1":"api-1","f2":"api-2","f3":"api-3","f4":"api-4","f5":"api-5"}}]}'
```
and on topics-ui I still can see "data type: binary" and this is the content od the topic as it is shown on "ra data" tab:
```
[
  {
    "topic": "avrotest2",
    "key": "ée",
    "value": "\u0000\u0000\u0000\u0002G\napi-1\napi-2\napi-3\napi-4\napi-5",
    "partition": 0,
    "offset": 0
  }
]
```
I guess I'm not the only one with this problem..

Thanks in advance

**Comment by mattferroni** [comment]
Hi there,
I'm experiencing the same issue here: any news on how to fix it?
Thanks in advance!

**Comment by mtj8033** [comment]
Is there any plans to support other naming strategies? 

https://docs.confluent.io/current/schema-registry/docs/serializer-formatter.html#subject-name-strategy

**Comment by andmarios** [comment]
Hi @mtj8033, you have to configure your Kafka REST proxy to use your own naming strategy. It's not a setting you can change from Kafka Topics UI which only uses the API Kafka REST provides.

**Comment by jglambed** [comment]
Closed as not supported
