### ISSUE TITLE
Basic Auth for Kafka topics UI

### ISSUE THREAD

**Issue by ankitagupta12** [Landoop/kafka-topics-ui#122]
This issue is related to:
https://github.com/Landoop/kafka-topics-ui/issues/103

I am using `KAFKA_TOPICS_UI_VERSION=0.9.3`
and i have added `-e CADDY_OPTIONS` too to my docker image. but the healthcheck endpoint on Landoop UI shows "Something went wrong". Wanted to check if basic auth is supported for the latest image or is it only supported for a specific version?

**Comment by ankitagupta12** [comment]
I'm assuming the "Something went wrong" is because of authentication issues but i'm not entirely sure. is there a way to verify?

**Comment by andmarios** [comment]
Hi @ankitagupta12. The `0.9.3` version of the image doesn't support basic auth as this was added later. Please use the `latest` instead.

That said, adding `-e CADDY_OPTIONS` to `0.9.3` shouldn't affect anything, so your problems come from elsewhere.

**Comment by ankitagupta12** [comment]
yeah you're right @andmarios . my problem is that the rest proxy server requires basic auth and sending basic auth credentials with the URL does not work. so are you saying if i switch to the latest version of the image, I should be able to specify the credentials in the URL?

**Comment by andmarios** [comment]
Ah, so you don't need basic auth to the Kafka Topics UI, rather to the REST Proxy.

In that case, just set the credentials in the URL you pass to the docker image. Something like:

```
docker run -e "KAFKA_REST_PROXY_URL=http://USER:PASSWORD@rest.url:8082" ...
```

I haven't tested it, but it should work.

**Comment by ankitagupta12** [comment]
I did so @andmarios and it doesn't work. it strongly seems like basic authentication is not supported. Angular.js's HttpFactory does not seem to support supplying basic authentication headers in URL, and kafka-topics-ui does not have explicit support for basic authentication.

I'm considering setting up a reverse proxy with which uses the plain url and then calls the URL with credentials to make this work, but it would have been great if what you suggested just worked as is

**Comment by andmarios** [comment]
Can you try with `-e PROXY=1` as well? It may help as in that case it is the caddy server that will perform the connection and not the browser.

**Comment by ankitagupta12** [comment]
hi @andmarios , okay tried with PROXY=true, and that works. thanks so much for your help!

**Comment by ankitagupta12** [comment]
closing this issue

**Comment by andmarios** [comment]
Glad it worked!
