### ISSUE TITLE
Kafka topis UI limits messages displayed despite changing MAX_BYTES and RECORD_POLL_TIMEOUT

### ISSUE THREAD

**Issue by ankitagupta12** [Landoop/kafka-topics-ui#124]
Hi,

I followed the discussion on this thread: https://github.com/Landoop/kafka-topics-ui/issues/107

and I set my `consumer.request.timeout.ms = 30000`. In addition I set 
``` "MAX_BYTES": "1000000",
  "RECORD_POLL_TIMEOUT": "12000"
```
but when i look at the UI, I only see messages that roughly amount to 50Kb when I download the messages as JSON.

I have two questions:
1. What is the impact of `RECORD_POLL_TIMEOUT`? I wasn't able to find sufficient documentation on this setting
2. Why is it that despite changing these settings I'm still seeing the same number of messages in the Kafka topics UI?

My rest proxy version is `3.3.0` and my Kafka topics UI version is `0.9.3`

**Comment by ankitagupta12** [comment]
actually it took a while to reflect, but it does reflect correclty now. i'd still very much appreciate answers to the first question:
```
What is the impact of RECORD_POLL_TIMEOUT? I wasn't able to find sufficient documentation on this setting

```

Otherwise the issue can be closed. thank you!

**Comment by Antwnis** [comment]
Hi @ankitagupta12 the backend (kafka-rest) is particularly slow when 
i) creating a new consumer group
ii) messages in the topic are relative large

Setting record-poll-timeout to 30 seconds, allows the backend sufficient time to get the messages

Different backends have different performance, so https://lenses.stream for example processes requests in < 1 sec  

I'll close this ticket - feel free to re-open
