### ISSUE TITLE
Basic Auth at REST Proxy

### ISSUE THREAD

**Issue by sergeiwaigant** [Landoop/kafka-topics-ui#128]
Hi all,

I'm looking for an option to authenticate the Topics UI against the REST Proxy over Basic Auth.
We have 2 REST Proxys behind a Citrix NetScaler Load Balancer and we need to authenticate at this HTTPS endpoint.

Any idea?

Kind regards
Sergei

**Comment by andmarios** [comment]
Hi @sergeiwaigant, you can authenticate to the rest proxies by using URL encoding for the basic auth credentials. That is you add them to the rest proxy URL. Like:

    http://[USER]:[PASSWORD]@rest.proxy.url

**Comment by sergeiwaigant** [comment]
Great, works, I could have thought it myself... thanks!

**Comment by andmarios** [comment]
Glad we tackled it! :grin:
