### ISSUE TITLE
No refreshing the changes on the code

### ISSUE THREAD

**Issue by esuarezz** [Landoop/kafka-topics-ui#136]
I am doing some changes in the code and it is not getting refreshed the changes...
I think grunt is failing, also without changing the code.

pm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated bower@1.3.12: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated npmconf@2.1.3: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! code E500
npm ERR! 500 Internal Server Error: grunt@^1.0.1

**Comment by jglambed** [comment]
As kafka-topics-ui is served through an http server you need to manually hard refresh the browser to get your code updates. Also you do not need to run grunt, if not for a production build. As per the node modules updates we are planning to fix them with an upcoming release.
