### ISSUE TITLE
protobuf message content

### ISSUE THREAD

**Issue by dlaflamme** [Landoop/kafka-topics-ui#137]
How can kafka-topics-ui be configured to deserialize messages in protobuf format?

**Comment by Antwnis** [comment]
The backend service does not support protobuf.

Protobuf support is there in https://Lenses.io though

**Comment by dlaflamme** [comment]
Doesnt lenses use kafka-topics-ui for the topics UI functionality? I guess I was assuming it did and since lenses supported deserializing protobuf, kafka-topics-ui would as well.

**Comment by Antwnis** [comment]
Lenses state-of-the-art product, with it's own APIs, whereas kafka-topics-ui is more of a 2015-2016 era
