### ISSUE TITLE
Getting 400 for topic/partition

### ISSUE THREAD

**Issue by amit4767** [Landoop/kafka-topics-ui#139]
1. I am using confluent Schema Registry and Kafa-rest.
2. Update required thing in properties file like bootstrap sever etc.
3. hostname:8000/api/kafka-rest-proxy/topics/amittest/partitions (is working fine when I hit from broswer)
4. but getting error in landoop UI.
All the end is working fine but getting 400 response when "proxy/topics/_schemas/partitions"
(anonymous) @ angular.js:14525
angular.js:14525 Possibly unhandled rejection: Failed at method [GET] [/api/kafka-rest-proxy/topics/_schemas/partitions] with error: 
{"data":"","status":400,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/kafka-rest-proxy/topics/_schemas/partitions","data":"","dataType":"json","headers":{"Content-Type":"","Accept":"application/vnd.kafka.v2+json, application/vnd.kafka+json, application/json"}},"statusText":"Bad Request"}

**Comment by jglambed** [comment]
This is most likelly a CP version issue. As per readme description 

> Latest release is for CP 3.2.0 and above.
> 
> For versions older than CP 3.2.0 you will need kafka topics ui version 0.8.3.

If version does not solve your issue feel free to reopen this ticket.

Cheers,
John
