### ISSUE TITLE
Error at loading topic-records

### ISSUE THREAD

**Issue by acr-dob** [Landoop/kafka-topics-ui#141]
I'm running a kafka-rest and kafka-topics-ui docker container in my dev-environment.

The number of topics and the names of topics are correctly loaded.

However, when chosing a topic, the data records are not loaded. The browsers console shows following error log:

Failed at method [GET] [/api/kafka-rest-proxy/consumers/kafka_topics_ui_avro_2019-01-08-10-53-13-904/instances/kafka-topics-ui-avro/records?timeout=8000&max_bytes=50000] with error: 
{"data":"avro format does not supported","status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/kafka-rest-proxy/consumers/kafka_topics_ui_avro_2019-01-08-10-53-13-904/instances/kafka-topics-ui-avro/records?timeout=8000&max_bytes=50000","data":"","dataType":"json","headers":{"Content-Type":"application/vnd.kafka.v2+json","Accept":"application/vnd.kafka.avro.v2+json"}},"statusText":"Not Found"}

Does someone know what is the cause for this?

Regards Klaus

**Comment by jglambed** [comment]
Kafka Topics UI is trying to deserialise Records from Kafka in three steps.

1. Makes an assumption that data are in AVRO format. If that fails, continues in step 2.
2. Makes an assumption that data are in JSON format. If that fails, continues in step 3.
3. Tries to read data as BYTES which should always succeed. 

In your case, it looks like that AVRO format fails, and it should continue trying by creating a JSON deserialiser. Are there any other logs available?

Also which version of CP are you using?

**Comment by mariosant** [comment]
Closed due to inactivity. Please feel free to reopen if any updates.
