### ISSUE TITLE
Topics data not loading

### ISSUE THREAD

**Issue by Arkoprabho** [Landoop/kafka-topics-ui#143]
I am trying to deploy kafka-topics-ui on a kubernetes cluster with helm. I have the kafka-cluster up and running, along with cp-schema-registry and cp-kafka-rest proxy. The kafka-topics-ui is exposed using a LoadBalancer. The output of `kubectl get all` is as follows:
```
NAME                                                       READY   STATUS    RESTARTS   AGE
pod/laughing-peacock-cp-kafka-rest-78b4dd8d89-flfds        2/2     Running   1          3m
pod/laughing-peacock-cp-schema-registry-84d7f5f986-x86zp   2/2     Running   3          3m
pod/laughing-peacock-kafka-0                               1/1     Running   1          3m
pod/laughing-peacock-lenses-6ddd9f9cb9-fq6gn               1/1     Running   0          3m
pod/laughing-peacock-zookeeper-0                           1/1     Running   0          3m
pod/testclient                                             1/1     Running   0          1h

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)                      AGE
service/kubernetes                            ClusterIP      10.31.240.1     <none>           443/TCP                      7d
service/laughing-peacock-cp-kafka-rest        ClusterIP      10.31.241.23    <none>           8082/TCP                     3m
service/laughing-peacock-cp-schema-registry   ClusterIP      10.31.251.254   <none>           8081/TCP                     3m
service/laughing-peacock-kafka                ClusterIP      10.31.247.190   <none>           9092/TCP,9901/TCP            3m
service/laughing-peacock-kafka-headless       ClusterIP      None            <none>           9092/TCP                     3m
service/laughing-peacock-lenses               LoadBalancer   10.31.241.105   <redacted>       80:31132/TCP                 3m
service/laughing-peacock-zookeeper            ClusterIP      10.31.249.180   <none>           2181/TCP                     3m
service/laughing-peacock-zookeeper-headless   ClusterIP      None            <none>           2181/TCP,3888/TCP,2888/TCP   3m

NAME                                                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/laughing-peacock-cp-kafka-rest        1         1         1            1           3m
deployment.apps/laughing-peacock-cp-schema-registry   1         1         1            1           3m
deployment.apps/laughing-peacock-lenses               1         1         1            1           3m

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/laughing-peacock-cp-kafka-rest-78b4dd8d89        1         1         1       3m
replicaset.apps/laughing-peacock-cp-schema-registry-84d7f5f986   1         1         1       3m
replicaset.apps/laughing-peacock-lenses-6ddd9f9cb9               1         1         1       3m

NAME                                          DESIRED   CURRENT   AGE
statefulset.apps/laughing-peacock-kafka       1         1         3m
statefulset.apps/laughing-peacock-zookeeper   1         1         3m
```
I notice that the endpoint is up and working. It detects the topics and the brokers correctly.

**ISSUE**: On trying to explore more about a topic, I get an infinitely loading page that seems to never get a response. The point at which it seems to be stuck is http://redacted.ip/api/kafka-rest-proxy/consumers/kafka_topics_ui_avro_2019-02-06-04-58-38-567/instances/kafka-topics-ui-avro/records?timeout=2000&max_bytes=50000

Some details about the configuration
Kafka Topic UI Version: KAFKA-TOPICS-UI v0.9.4 (from docker image)
Kafka cluster deployed using: [helm chart](https://github.com/helm/charts/tree/master/incubator/kafka) with default settings
Rest proxy and schema registry deployed using: [cp-chart](https://github.com/confluentinc/cp-helm-charts/tree/master/charts)

**Comment by Arkoprabho** [comment]
UPDATE: The metadata is being received by the topics UI on the URL: `http://0.0.0.0:8000/api/kafka-rest-proxy/topics/testpt` and `http://0.0.0.0:8000/api/kafka-rest-proxy/topics/testpt/partitions`.
But this data does not end up in the UI

**Comment by jglambed** [comment]
Can you please share any logs from the browser?
It could be a timeout that could be resolved by changing the `RECORD_POLL_TIMEOUT` but I cannot tell for sure without more information

**Comment by mariosant** [comment]
Closed due to inactivity. Please feel free to reopen if any updates.

**Comment by dimisjim** [comment]
@jglambed what's the default `RECORD_POLL_TIMEOUT` value? I am also don't see topic data in big topics.
