### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by sachnk** [Landoop/kafka-topics-ui#147]
Hey --

My understanding is that the newer versions of Kafka provide timestamps in every message. Is there a way to show this information when inspecting messaging?

Thanks

**Comment by mariosant** [comment]
Hey @sachnk, thanks for the feedback! I am afraid Confluent's REST Proxy API (which kafka-topics-ui utilizes) does not provide that, at the time of writing.

Our flagship product though, does. It's free to use for developers, so you might want to [give it a go](https://lenses.io/downloads/).
