### ISSUE TITLE
url subpath

### ISSUE THREAD

**Issue by kiddo3** [Landoop/kafka-topics-ui#149]
Hi,
I'm trying to publish the topics ui using docker image and kubernetes nginx ingress to a subpath like: www.test.com/ui/topics
But I can't make it work in a subpath, it's possible to configure it to work in a url subpath ? 
Thanks in advance

**Comment by mariosant** [comment]
Hey @kiddo3, this is a feature we don't have in our roadmap. Maybe you can achieve this by setting nginx to work as a reverse proxy.

Please take a look at the following link, it might be useful for your case.
https://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite
