### ISSUE TITLE
KAFKA REST /api/kafka-rest-proxy CONNECTIVITY ERROR

### ISSUE THREAD

**Issue by ankit45621** [Landoop/kafka-topics-ui#150]
Hi,

I am getting same issue with configuration:
version: '2'
services:
zookeeper:
image: confluentinc/cp-zookeeper:5.2.2
ports:
- 32181:32181
volumes:
- "/vol1/zk-data:/var/lib/zookeeper/data"
- "/vol2/zk-txn-logs:/var/lib/zookeeper/log"
environment:
ZOOKEEPER_CLIENT_PORT: 32181
ZOOKEEPER_TICK_TIME: 2000

kafka:
image: confluentinc/cp-kafka:5.2.2
volumes:
- "/vol3/kafka-data:/var/lib/kafka/data"
depends_on:
- zookeeper
ports:
- 29092:29092
environment:
KAFKA_BROKER_ID: 1
KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
KAFKA_LISTENERS: LISTENER_BOB://kafka:9092,LISTENER_FRED://0.0.0.0:29092
KAFKA_ADVERTISED_LISTENERS: LISTENER_FRED://test.moglix.com:29092,LISTENER_BOB://kafka:9092
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
KAFKA_CONFIG_STORAGE_REPLICATION_FACTOR: 1
KAFKA_STATUS_STORAGE_REPLICATION_FACTOR: 1

kafkaconnectjdbc:
image: confluentinc/cp-kafka-connect
network_mode: host
hostname: localhost
depends_on:
- zookeeper
- kafka
ports:
- "48083:48083"
volumes:
- /tmp/quickstart/file:/tmp/quickstart
- /etc/jars:/etc/kafka-connect/jars
environment:
CONNECT_BOOTSTRAP_SERVERS: 'localhost:29092'
CONNECT_REST_ADVERTISED_HOST_NAME: localhost
CONNECT_REST_PORT: 48083
CONNECT_GROUP_ID: compose-connect-group
CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
CONNECT_ZOOKEEPER_CONNECT: 'localhost:32181'
CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
CONNECT_PLUGIN_PATH: '/usr/share/java,/etc/kafka-connect/jars'

debezium:
image: debezium/connect:0.9
depends_on:
- zookeeper
- kafka
ports:
- "38083:38083"
environment:
BOOTSTRAP_SERVERS: 'kafka:9092'
REST_ADVERTISED_HOST_NAME: localhost
REST_PORT: 38083
GROUP_ID: debezium-connect-group
CONFIG_STORAGE_TOPIC: docker-debezium-configs
CONFIG_STORAGE_REPLICATION_FACTOR: 1
OFFSET_FLUSH_INTERVAL_MS: 10000
OFFSET_STORAGE_TOPIC: docker-debezium-offsets
OFFSET_STORAGE_REPLICATION_FACTOR: 1
STATUS_STORAGE_TOPIC: docker-debezium-status
STATUS_STORAGE_REPLICATION_FACTOR: 1
KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
ZOOKEEPER_CONNECT: 'zookeeper:32181'
kafka-rest-proxy:
image: confluentinc/cp-kafka-rest:5.2.2
container_name: kafka-rest-proxy
network_mode: host
restart: unless-stopped
depends_on:
- zookeeper
- kafka
ports:
- "8082:8082"
environment:
KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:32181
KAFKA_REST_HOST_NAME: kafka-rest-proxy
KAFKA_REST_LISTENERS: http://0.0.0.0:8082
KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 40000

kafka-topics-ui:
image: landoop/kafka-topics-ui:0.9.4
container_name: kafka-topics-ui
restart: unless-stopped
depends_on:
- kafka-rest-proxy
ports:
- "8085:8000"
environment:
KAFKA_REST_PROXY_URL: http://kafka-rest-proxy:8082
PROXY: "true"

Logs:

Landoop Kafka Topics UI 0.9.4
Visit https://github.com/Landoop/kafka-topics-ui/tree/master/docker
to find more about how you can configure this container.

Enabling proxy.
Kafka REST Proxy URL to /api/kafka-rest-proxy.

Activating privacy features... done.
http://0.0.0.0:8000
172.21.0.1 - - [17/Sep/2019:07:42:36 +0000] "GET /env.js HTTP/1.0" 200 181
172.21.0.1 - - [17/Sep/2019:07:42:37 +0000] "GET /api/kafka-rest-proxy/topics HTTP/1.0" 502 16
172.21.0.1 - - [17/Sep/2019:07:42:37 +0000] "GET /api/kafka-rest-proxy/brokers HTTP/1.0" 502 16
172.21.0.1 - - [17/Sep/2019:07:42:37 +0000] "POST /api/kafka-rest-proxy/consumers/kafka_topics_ui_json_2019-09-17-01-12-21-342 HTTP/1.0" 502 16
172.21.0.1 - - [17/Sep/2019:07:42:37 +0000] "GET /api/kafka-rest-proxy/topics HTTP/1.0" 502 16

Please help me with this issue.

**Comment by mariosant** [comment]
Hey @ankit45621, apologies for the delay. Sounds like network misconfiguration.
Closing this one for now, please feel free to reply if you feel it is an issue with kafka-topics-ui per se.
