### ISSUE TITLE
Set tag for the docker images

### ISSUE THREAD

**Issue by ivangfr** [Landoop/kafka-topics-ui#151]
Hi, I am using **landoop/kafka-topics-ui** version `0.9.4` and I would like to upgrade it.

I've seen that there is a new docker image in Docker Hub that was built 5 months ago with the tag `latest`. It'd be good if we have a version number, maybe following the sequence it would be `0.9.5`.

Best regards.

**Comment by mariosant** [comment]
Hi @ivangfr, no worries, we will make a release when we are ready to! :)
