### ISSUE TITLE
How to work with multi-broker?

### ISSUE THREAD

**Issue by gabrieldesousah** [Landoop/kafka-topics-ui#161]
How is opssible to connect with multiple brokers?

I am using kafka on kubernetes in amazon EKS, and I am using a port-forwarding:
`kubectl -n kafka port-forward svc/kafka-headless 9092`

After I up the docker:

```
docker pull landoop/kafka-topics-ui
docker run --rm -it -p 39292:8000 \
  -e "KAFKA_REST_PROXY_URL=http://kafka-helm-0.localhost:9092,kafka-helm-1.localhost:9092"\
  -e "PROXY=true" \
  landoop/kafka-topics-ui
```

But I can't connect with kafka in localhost... What I need to do?
![Anotação 2020-03-04 162129](https://user-images.githubusercontent.com/11802211/75914882-465c8400-5e34-11ea-8f60-ad0aa23274a3.png)

**Comment by mariosant** [comment]
Hi @gabrieldesousah! This project needs Confluent's kafka rest service to connect to and in my understanding is that you don't use it.

At this point, I would suggest taking a look at our [flagship product](https://lenses.io) as a turnkey solution.
