### ISSUE TITLE
Display First & Last Offset To Seek

### ISSUE THREAD

**Issue by Alsheh** [Landoop/kafka-topics-ui#164]
I think displaying the first and last offset and size (size=last_offset-first_offset) for a topic will help tremendously while inspecting topic messages using the seek feature.

Great tool, thanks!

**Comment by mariosant** [comment]
Thank you @Alsheh ! This feature unfortunately is not on our roadmap. Feel free to use our [Lenses.io](https://lenses.io) product which has a better seek functionality.
