### ISSUE TITLE
local ?

### ISSUE THREAD

**Issue by walshe** [Landoop/kafka-topics-ui#166]
Can I use this to connect to the kafka server on my local machine at 9092 ?

**Comment by mariosant** [comment]
Hi @walshe, technically yes. You would need to run a local Kafka instance and a Confluent Rest Proxy instance though. You can then configure kafka-topics-ui to connect to your local rest proxy.

You might find it easier to use our [Lenses Box](https://lenses.io/downloads/lenses/?path=wizard-form) which comes in the form of a simple docker image. It's free as well.
