### ISSUE TITLE
Use Strimzi kafka bridge instead of kafka rest proxy 

### ISSUE THREAD

**Issue by OuesFa** [Landoop/kafka-topics-ui#167]
Hello guys ! 
Is it possible to setup kafka-topics-ui using [Strimzi kafka bridge](https://github.com/strimzi/strimzi-kafka-bridge) api instead of confluent rest proxy please ?
Thank you !

**Comment by mariosant** [comment]
Hello @OuesFa! Thanks for reaching out! This project is using Confluent's Kafka Rest Proxy as a data source and supporting another one is not in our current roadmap.

Having said this, if you would like to see this feature, feel free to submit a PR to support it.
