### ISSUE TITLE
kafka topic ui connectivity error

### ISSUE THREAD

**Issue by manee2k6** [Landoop/kafka-topics-ui#168]
Here is the configuration i am using to integrate kafka topic ui in docker swarm cluster.

i notice connectivity error, as i have kafka cluster with 3 zookeeper and broker running.
kafka-ui:
    image: landoop/kafka-topics-ui
    networks:
      - internal
      - traefik-net
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest:8082"
      PROXY: "true"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://xxxxxxxxx:2209"
        tag: "kafka-ui"
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:xxxxxxx.com"
        - "traefik.frontend.whiteList.useXForwardedFor=true"
        - "traefik.port=8000"
        - "traefik.enable=true"
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 500M
          cpus: '0.50'
        reservations:
          cpus: '0.1'
          memory: 100M

**Comment by mariosant** [comment]
Hi @manee2k6, thanks for reporting this. `kafka-topic-ui` needs to connect to a Confluent REST Proxy API. Can you please confirm it's working as expected?

**Comment by mariosant** [comment]
Closed due to inactivity.
