### ISSUE TITLE
Make it possible to use without schema registry

### ISSUE THREAD

**Issue by jeffwidman** [Landoop/kafka-topics-ui#21]
We use Kafka without a schema registry, just use JSON for everything. 

Can I use this UI without a schema registry? The docs for running with docker seem to imply no.

**Comment by chdask** [comment]
Hi @jeffwidman, thanks for the request. 
We are in process of cleaning up the code of any schema registry dependency. I think the current release is not depending on it, functionality wise. However, keep in mind that kafka-rest, which is the current endpoint, requires access to the schema registry service. 

We will also release our own backend to provide enhanced features to the kafka-topics-ui.

**Comment by jeffwidman** [comment]
My understanding is that kafka-rest doesn't require access to a schema registry service... one of my coworkers just completed some tests using kafka-rest without ever setting up a schema registry and it worked fine for him. 

Do you know something we don't?

**Comment by Antwnis** [comment]
@jeffwidman i'm understanding you are posting JSON and you would like to `exercise just the json consumer` 

On Kafka Rest avro consumer uses the schema-registry service - so to your particular use-case (JSON Only) your backend (Kafka-Rest) does not require the schema-registry

From our side - a design we could do is introduce a param / argument like

`disable_avro: boolean`

That you set to true if you work on JSON only. Then our UI would be intelligent to skip a number of API calls we do at initialization...

So there is a nice improvement we can do - based on your suggestion 

Will keep you posted

**Comment by andmarios** [comment]
Kafka-topics-ui indeed works without the schema registry. For JSON topics it will provide topic and table views. For binary topics it will only provide raw data.

@jeffwidman you can run the docker image like this:

```
 docker run --rm -it -p 8000:8000 \
            -e "KAFKA_REST_PROXY_URL=http://<REST-PROXY>:8082" \
            landoop/kafka-topics-ui
```

Alternatively, just throw the release under any web server and adjust your REST proxy URL inside `combined.js` at line 96 (we should make this more easy to set). :)
