### ISSUE TITLE
vote for this to work via direct contact to brokers

### ISSUE THREAD

**Issue by dollschasingmen** [Landoop/kafka-topics-ui#24]
The readme says there are plans to have this work not only through the rest proxy. Would be nice if we could just connect via a list of brokers:ports.

**Comment by Antwnis** [comment]
That would be kinda of hard @dollschasingmen 

This around this - a javascript application talking with the binary protocol of kafka - directly to the brokers ... 

The alternative would be a small custom build backend that serves the UI through web-sockets and provides enhanced querying and monitoring capabilities over your topics etc...

This is the future we are envisioning ..

**Comment by dollschasingmen** [comment]
hmm an the backend would be like java/scala or something which would make it easier to connect to brokers directly? currently we are using kafka-manager which takes zookeeper hosts:

https://github.com/yahoo/kafka-manager

but i personally find that the UI in kafka-topics-ui is much better.

**Comment by jeffwidman** [comment]
Why spend the dev cycles on a custom backend? Why not just use the REST api? It's trivial to setup one using a docker container: https://github.com/DockerKafka/confluent-kafka-rest-docker

This setup could be made easier though, see #23 

Startups are successful by saying "no" far more often than "yes" when it comes to building out tons of features.

**Comment by mariosant** [comment]
Hi everyone! Feel free to try our [Lenses.io product](https://lenses.io/) that does exactly that.
