### ISSUE TITLE
Add nginx to docker image

### ISSUE THREAD

**Issue by mabn** [Landoop/kafka-topics-ui#26]
It would be great it docker image had nginx setup adding required CORS headers. Right now it just does not work if kafka runs somewhere else.

**Comment by andmarios** [comment]
We do offer the functionality but you have to enable it explicitly, as it would be irresponsible on our part to proxy your Kafka REST Proxy endpoint by default.

To use it, pass `-e "PROXY=true"` to docker, like:

```
docker run --rm -it -p 8000:8000 \
           -e "KAFKA_REST_PROXY_URL=http://kafka.rest.proxy.url" \
           -e "PROXY=true" \
           landoop/kafka-topics-ui
```

**Comment by andmarios** [comment]
Since there are no updates and the proxy functionality (albeit not from nginx) is there, I will close the issue for now. Feel free to comment or open a new one if needed.

**Comment by mabn** [comment]
I didn't know that it's possible to use PROXY=true. Thanks.
