### ISSUE TITLE
Create DC/OS universe component

### ISSUE THREAD

**Issue by Antwnis** [Landoop/kafka-topics-ui#3]
https://github.com/mesosphere/universe/

**Comment by todormazgalov** [comment]
Hello, I can't locate the component in the DC/OS repository. Where exactly can I find it? Thanks!

**Comment by Antwnis** [comment]
There is no DC/OS component yet
What could be of use is our fast-data-dev docker -> https://github.com/Landoop/fast-data-dev

**Comment by Antwnis** [comment]
Closing as no immediate plans to release into the DC/OS universe
