### ISSUE TITLE
Avro or Json deserialization can wrongly be considered as failed

### ISSUE THREAD

**Issue by laymain** [Landoop/kafka-topics-ui#39]
Hi,

If the Avro message contains "error" (or if the Json message contains "error_code"),
the deserialization will be considered as failed even if it has succeeded.

It seems that the code responsible of that issue is this error handling:
```javascript
    var dataPromiseAvro = KafkaRestProxyFactory.consumeKafkaRest("avro", $scope.topicName);
    dataPromiseAvro.then(function (allData) {
      if (JSON.stringify(allData).indexOf("error") > 0) {
        $log.warn('Failed with Avro - going to try with Json this time (' + allData + ')');
        var dataPromiseAvro = KafkaRestProxyFactory.consumeKafkaRest("json", $scope.topicName);
        dataPromiseAvro.then(
          function (allData) {
            if (JSON.stringify(allData).indexOf("error_code") > 0) {
              $log.warn('Failed with JSon as well - going to try with Binary this time (' + allData + ')');
```
https://github.com/Landoop/kafka-topics-ui/blob/179c8c445455ab4924e595a4eaf6d4215f010e9a/src/kafka-topics/view/view.controller.js#L343

**Comment by jglambed** [comment]
Thank you for mentioning that. We are investigating this issue for a better global solution.
