### ISSUE TITLE
Old consumer remain if the consumer failed to retrieve data

### ISSUE THREAD

**Issue by BDeus** [Landoop/kafka-topics-ui#44]
I have a lot of old consumers in zookeeper. 
When an error throw at consumer time it seems that the consumer instance is not deleted.
The consumer name is timestamped so it is not reusable. 
It is usefull to keep it?

**Comment by Antwnis** [comment]
Thanks for posting this issues. We noticed the same thing recently, and investigating whether this is an issue related to Kafka REST service (i.e. deletion is not purging the consumer group) or an issue on our code

Best solution would be to re-use the same consumer-group, but need to find a way to re-wind the offsets

**Comment by Antwnis** [comment]
So after investigating a little bit this seems to be a problem upstream in the `Kafka Rest` service itself

https://github.com/confluentinc/kafka-rest/issues/148

Kafka Rest cannot clean-up old consumer-groups. 

We will provide a nice solution to this by introducing an improved backend in our next release

btw on the schema-registry-ui we did a new release --> https://github.com/Landoop/schema-registry-ui/releases/tag/v.0.9.0

**Comment by Antwnis** [comment]
As per the latest topics-ui release (0.9.1) available @ https://github.com/Landoop/kafka-topics-ui/releases the v2 apis of 0.10.2.0 are used

Those new apis do not store consumers in the ZK - so this problem goes away 👍
