### ISSUE TITLE
New release 0.8.2?

### ISSUE THREAD

**Issue by BDeus** [Landoop/kafka-topics-ui#45]
Hello,
do you know when could you make a new release?
There is a lots of bugs fixes that i'm interested in.
Thanks

**Comment by Antwnis** [comment]
Hi Basile.

Planning on making a release on https://github.com/landoop/schema-registry-ui/ by tomorrow, adding a number of improvements, including exporting your schemas from a schema-registry ( for both backup - and an easy way to propagate your schemas i.e. from DEV -> UAT).

Next release on kafka-topics-ui will probably be early next week, and that would address your previously created ticket.

Please do **star** the (github) repositories that you like/use as our team is using that metric as feedback on where to focus next

Thanks - Antonios

**Comment by BDeus** [comment]
Thanks for the feedback.
I actually use docker to deploy this UI (schema-registry-ui too) to help on our debug.
It will be great if docker container can be versionned too.
Great job for all the work 👍

**Comment by simplesteph** [comment]
Thanks @Antwnis 
Can you please make sure to tag your releases?
https://hub.docker.com/r/landoop/kafka-topics-ui/tags/

**Comment by andmarios** [comment]
There is both a 0.8.2 release and tags now: https://hub.docker.com/r/landoop/kafka-topics-ui/tags/

I will close the issue but feel free to comment if something's off!
