### ISSUE TITLE
Docker Hub tags

### ISSUE THREAD

**Issue by davidnortonjr** [Landoop/kafka-topics-ui#46]
It would be helpful to have versioned Docker Hub tags in addition to the `latest` tag. This would help guard against unexpected change.

Thanks!

**Comment by andmarios** [comment]
Hey, a bit late but we added tags shortly after your comment: https://hub.docker.com/r/landoop/kafka-topics-ui/tags/

I'll close the report but feel free to comment if needed.

**Comment by davidnortonjr** [comment]
Thanks!
