### ISSUE TITLE
UI fails to parse specific topic names

### ISSUE THREAD

**Issue by andrei-tytsik** [Landoop/kafka-topics-ui#5]
Hi,
I've got "parse syntax" errors in console if there is at least one topic has name starting with numeric symbols (for example "123topic").
Kafka topic name regex is "[a-zA-Z0-9\._\-]", so "123topic" name is quite legal.

**Comment by Antwnis** [comment]
Thanks for that ! I was pushing 100% on making this release 
https://github.com/landoop/schema-registry-ui#version-06-16-aug-16

By the weekend i will be focusing on kafka-topics-ui and attend to many details like the one you just mentioned - will keep you posted

**Comment by Antwnis** [comment]
@andrewtyt please have a look at the latest release (v0.7) of this project
Many many improvements - and as far as topic - i can see a topic `123` - hope this works for you too as well

**Comment by chdask** [comment]
I think this should be ok with the 0.7.1 #14 fix. Closing the issue.
