### ISSUE TITLE
Incorrect parsing of message key produces bad table display

### ISSUE THREAD

**Issue by kinghuang** [Landoop/kafka-topics-ui#52]
**Description**

kafka-topics-ui seems to parse plain string message keys incorrectly when displaying messages in a table, interpreting the length of the key string as the number of fields in the key. This results in offset table rows for messages, with values that no longer line up to the table headers.

**Steps to reproduce the issue:**

1. Produce messages to a Kafka topic whose key are plain strings.
2. View the topic in kafka-topics-ui in the table view.

**Describe the results you received:**

Assuming the key is a 5 character string, the table view generates 5 columns under key, but outputs a single table element consisting of the 5 character key. This results in the message value being pulled into the key columns by 4 (see picture).

![screen shot 2017-02-21 at 2 19 16 pm](https://cloud.githubusercontent.com/assets/27340/23185469/c2254b92-f840-11e6-9710-a0f68ea83648.png)

**Describe the results you expected:**

For the above screenshot, there should be a single column for the key. The remaining row cells (`UCP01`, `1000`, `00001`, etc.) should line up under `BUSINESS_UNIT`, `PROJECT_ID`, `ACTIVITY_ID`, etc. Something like this constructed screenshot.

![screen shot 2017-02-21 at 2 30 11 pm](https://cloud.githubusercontent.com/assets/27340/23185906/5129a5da-f842-11e6-821d-cd4aaf128248.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

Using `landoop/kafka-topics-ui:0.8.1`.

Here's a screenshot of the topic view, showing the correct data.

![screen shot 2017-02-21 at 2 21 21 pm](https://cloud.githubusercontent.com/assets/27340/23185608/2f3af8bc-f841-11e6-8d6e-54096bc36ca8.png)

**Comment by jglambed** [comment]
Thank you for the feedback, we will have to take a closer look and come back with a proper solution

**Comment by Antwnis** [comment]
Hi @kinghuang 

A fix has been pushed. If you use the latest code, the issue should be addresses
We will also make a new release soon, to provide the fix on the docker images etc 

So 0.8.2 will be released later on today

**Comment by kinghuang** [comment]
Just tried with the `landoop/kafka-topics-ui:0.8.2` image. I confirm it's fixed for my example case. Thanks!
