### ISSUE TITLE
Kafka Topics UI with uppercase character

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-topics-ui#54]
If my topic is called `my.Topic` for example, and it's an avro topic, the schema registry ui will show the uppercase fine, and will show the schema fine as well, but the topics UI will try to retrieve the schema in the lowercase form and display the topic in the lowercase form, therefore displaying an "topic empty" error

**Comment by Antwnis** [comment]
Doing a bit of re-validation:

```
docker run --rm -p 2181:2181 -p 3030:3030 -p 8081-8083:8081-8083 \
           -p 9581-9585:9581-9585 -p 9092:9092 -e ADV_HOST=192.168.99.100 \
           landoop/fast-data-dev
```

Then on another terminal

```
docker run --rm -it --entrypoint bash landoop/fast-data-dev

kafka-avro-console-producer --broker-list 192.168.99.100:9092 --topic my.Topic --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}' --property schema.registry.url=http://192.168.99.100:8081
```

And entering a few values from the console:

```
{"f1": "value1"}
```

**my.Topic** works on schema-registry & on kafka-topics

Closing as it has been addressed
