### ISSUE TITLE
How to specify Schema Registry URL?

### ISSUE THREAD

**Issue by kinghuang** [Landoop/kafka-topics-ui#55]
How do I specify the Schema Registry URL when running as a Docker container? The only mention of the Schema Registry seems to be the README saying that it's optional.

**Comment by Antwnis** [comment]
You don't need to specify the schema-registry service URL as per this docker
This location will need to be specified in the backend service (Kafka-REST) to assist in the de-serialization process, but not on the kafka-topics-ui as per ce

**Comment by kinghuang** [comment]
Ah, I didn't realize Kafka REST was handling it. I'll set it there. Thanks!
