### ISSUE TITLE
Feature Request: Optionally display more than 10 items in topic and table views

### ISSUE THREAD

**Issue by kinghuang** [Landoop/kafka-topics-ui#56]
**Description**

When viewing a topic, the `TOPIC` and `TABLE` views display 10 items per page. For a topic with a large number of messages on a large display, this results in a suboptimal display of items due to the need to paginate extensively and unused screen real estate.

It would be useful to have an option to show more than 10 items per page to make it easier to scan through large topics and use available screen real estate.

**Steps to reproduce the issue:**
1. Have a topic with a large number of messages. In my example, I am browsing topics with over 100 messages.
2. In `kafka-topics-ui`, select the topic and look at the `TOPIC` and `TABLE` views.

**Describe the results you received:**

Both the `TOPIC` and `TABLE` views are limited to 10 items per page.

**Describe the results you expected:**

I would like the views to display a user selectable number of items per page. There should also be a way to set a default number of items per page.

**Additional information you deem important (e.g. issue happens only occasionally):**

The observations are based on the `landoop/kafka-topics-ui:0.8.2` Docker image.

![screen shot 2017-03-01 at 10 36 56 am](https://cloud.githubusercontent.com/assets/27340/23472823/58b270b4-fe6b-11e6-8157-bc9bf3a39844.png)

**Comment by Antwnis** [comment]
Excellent issue report @kinghuang 

We'll implement similar capability to the schema-registry-ui where the number of lines display-able in the pagination of both the (topics-list) and the (messages-list) is dynamically configured based on your screen-size. 

i.e. Based on your screenshot it would display ~35 kafka messages / screen

additionally we could add a custom selector on a i.e. bottom right corner to allow you to specify the exact pagination requested (i.e. every 50 messages)

**Comment by kinghuang** [comment]
That sounds great, @Antwnis!

My personal preference is to be able to specify the exact pagination. I'd like to be able to scroll over say 100 messages at a time before changing pages.
