### ISSUE TITLE
Make v2 API calls by default with REST Proxy 3.2.0

### ISSUE THREAD

**Issue by simplesteph** [Landoop/kafka-topics-ui#58]
The REST Proxy has been updated to leverage the new consumer http://docs.confluent.io/3.2.0/kafka-rest/docs/intro.html#produce-and-consume-avro-messages 

We need to have Kafka topics UI switch its API calls to v2 with a config (?)

**Comment by simplesteph** [comment]
Btw as soon as I enable Zookeeper security, the Kafka Topics UI is broken (which is expected). Therefore v2 is the only way for us to have the landoop topics ui work.

**Comment by andmarios** [comment]
Out of curiosity, what do you mean by “enable Zookeeper security”? Kerberos and ACLs on topics?

**Comment by simplesteph** [comment]
Yes
Plus zookeeper.set.acl=true

**Comment by Antwnis** [comment]
Closing as per release 0.9.1 https://github.com/Landoop/kafka-topics-ui/releases the topics-ui uses the v2 apis
