### ISSUE TITLE
docker image env SCHEMAREGISTRY_UI_URL has no effect

### ISSUE THREAD

**Issue by juyttenh** [Landoop/kafka-topics-ui#6]
Configured SCHEMAREGISTRY_UI_URL env variable, but in the UI it still refers to http://schema-registry-ui.landoop.com.

**Comment by andmarios** [comment]
Thanks for the report! We just fixed it with commit 546e2b25789977d3c46dfee8fb2d30a72c599ffb and bumped the docker image to the 0.7 release!
