### ISSUE TITLE
Please minify and pack javascript code in docker image

### ISSUE THREAD

**Issue by sailxjx** [Landoop/kafka-topics-ui#60]
Loading from separating assets is really slow, please minify and pack the javascript and css when build docker images.

<img width="1675" alt="2017-03-15 14 21 09" src="https://cloud.githubusercontent.com/assets/909853/23936142/352332fc-098b-11e7-9ac6-bbe695f72baf.png">

**Comment by mariosant** [comment]
Hi @sailxjx! Thanks for the suggestion, but we don't currently have plans for optimizing the assets pipeline. You can however submit a PR that implements this or, switch to our [Lenses product](https://lenses.io) that already utilizes an asset optimization workflow.
