### ISSUE TITLE
Docker Hub image for 0.8.3/latest failed to build

### ISSUE THREAD

**Issue by kinghuang** [Landoop/kafka-topics-ui#62]
The `latest` tag failed to build on Docker Hub for the 0.8.3 update.

https://hub.docker.com/r/landoop/kafka-topics-ui/builds/bwbrgffynfdpx2plbeqgggm/

**Comment by Antwnis** [comment]
Thanks @kinghuang 

Builds are now up-to date on dockerhub

https://hub.docker.com/r/landoop/kafka-topics-ui/builds/
