### ISSUE TITLE
CORS error with Confluent 3.2.0

### ISSUE THREAD

**Issue by haydursek** [Landoop/kafka-topics-ui#65]
Is this compatible with Confluent 3.2.0 as I keep getting a CORS error for some reason. I have defined the 'allows.control.access.origin=*' key in kafka-rest, and the 8.2 version of the UI was working for me with the same exact settings on Confluent 3.1.2. 

Also, I am able to send the same requests via Postman successfully.

**Comment by andmarios** [comment]
It should be compatible with 3.2.0. At least on the latest version (0.8.3).

Did you also set the `access.control.allow.methods=GET,POST,PUT,DELETE,OPTIONS` key?

Is there any error on your console (on Chrome it comes up with `CTRL+SHIFT+i`) that can helps us identify the issue?

**Comment by haydursek** [comment]
Hey thanks for the very prompt response, I did have that key in there but was missing one of the HTTP methods, but I got it working right after posting the message.

BTW, do you have a non-docker version of all 3 ui's consolidated into one ? I thought I had seen that on your site.

**Comment by andmarios** [comment]
Glad you figured it out! Unfortunately we don't have a consolidated version. 

Only on our fast-data-dev docker (an image for kafka development) you will find all three together, but again, they are actually separate, we just add a single page in the docker image that has links to all UIs.

They can work under a subdirectory though, so you can add all of them to your server if you want.

**Comment by haydursek** [comment]
Great thanks, and from the looks of them, they are all awesome tools !

**Comment by andmarios** [comment]
Thanks, we want to make Kafka as accessible as it gets!
