### ISSUE TITLE
Kafka-topic-ui doesn't start when project started from 'build from source'

### ISSUE THREAD

**Issue by vicchugu** [Landoop/kafka-topics-ui#66]
In any projects: **Kafka-topic-ui**, **kafka-connect-ui**, **schema-registry-ui**
when I choose to start application from "**Build from source**" I'm getting these errors (404):
In browser I can see only blank page.

http-server .
Starting up http-server, serving .
Available on:
  http://127.0.0.1:8080
  http://192.168.1.75:8080
Hit CTRL-C to stop the server
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/font-awesome/css/font-awesome.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/font-awesome/css/font-awesome.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/assets/css/styles.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/ace-builds/src-min-noconflict/ace.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/ace-builds/src-min-noconflict/ace.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /env.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/app.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/kafka.defaults.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/topics.config.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/factories/dirPagination.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/kafka-topics/home/home.controller.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/kafka-topics/view/view.controller.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/kafka-topics/config/config.controller.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/kafka-topics/list/topics-list.controller.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/factories/kafka-rest-proxy-factory.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/factories/env.factory.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/factories/utils-factory.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /src/factories/toast-factory.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:02 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:03 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/bootstrap/dist/css/bootstrap.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/font-awesome/css/font-awesome.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/font-awesome/css/font-awesome.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:06 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/ace-builds/src-min-noconflict/ace.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.css" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/ace-builds/src-min-noconflict/ace.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular/angular.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-ui-ace/ui-ace.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/spin.js/spin.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-spinner/angular-spinner.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-route/angular-route.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-material/angular-material.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-animate/angular-animate.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-aria/angular-aria.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-material-data-table/dist/md-data-table.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-ui-grid/ui-grid.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-base64/angular-base64.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/oboe/dist/oboe-browser.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-oboe/dist/angular-oboe.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/angular-json-tree/dist/angular-json-tree.min.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/handsontable/dist/handsontable.full.js" Error (404): "Not found"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0"
[Fri Apr 28 2017 13:18:07 GMT-0700 (PDT)] "GET /bower_components/ngHandsontable/dist/ngHandsontable.js" Error (404): "Not found"

**Comment by jglambed** [comment]
Thank you for your feedback.
It is probably because bower is not installed in your system.
Please try running:
` npm install -g bower `
` npm install`
`http-server .`

Let us know if that helps

**Comment by vicchugu** [comment]
Yes, it working now. Thanks, no errors in the console log.
But I've got different errors:
1. This is from ui:

Kafka Rest : localhost:8082
Kafka Brokers :
kafka-topics-ui: 0.8.3 **CONNECTIVITY ERROR**

if I run the curl from command line - curl http://localhost:8082/topics
["__confluent.support.metrics","__consumer_offsets","_schemas","test"]
This is looks correct (number of topics) . 
How can I setup debug  logging? 
In the right high corner I can see a pull down list of kafka clusters with 2 values prod and dev.
Is this a configurable future? I only had single broker/zookeper/schema-registry/kafka-rest settings on Mac (confluent platform).

Similar situation with **schema-registry-ui** project.

**Comment by vicchugu** [comment]
Both schema-registry-ui and kafka-topics-ui in docker versions working fine.

**Comment by andmarios** [comment]
I think the issue with your previous message, maybe was because you didn't use the schema (http) for the REST proxy address. Instead of `localhost:8082` try `http://localhost:8082`.

**Comment by vicchugu** [comment]
Based on docs I was using this command 'http-server .' to start kafka-topics-ui.

**Comment by vicchugu** [comment]
Tried http://localhost:8082, http://127.0.0.1:8082 - same result **CONNECTIVITY ERROR** (for both old and new version).

**Comment by Antwnis** [comment]
You should make sure that every single command completes successfully

    git clone https://github.com/Landoop/kafka-topics-ui.git
    cd kafka-topics-ui
    npm install -g bower
    bower install
    http-server .

Then you will have to **edit** your `env.js` file and add the IP address and port number of the Kafka Rest Proxy API.

Then you can use chrome to browse into the UI

**Comment by Antwnis** [comment]
Resolving as it builds & runs. Tried on Mac + Windows + Linux
