### ISSUE TITLE
Docker ignores schema registry url

### ISSUE THREAD

**Issue by apetheriotis** [Landoop/kafka-topics-ui#7]
schema registry url parameter gets ignored, when starting the docker container

`docker run --rm -it -p 8000:8000 
           -e "SCHEMAREGISTRY_UI_URL=localhost:8081" 
           -e "KAFKA_REST_PROXY_URL=localhost:8082"  
           landoop/kafka-topics-ui`

<img width="462" alt="screen shot 2016-09-05 at 16 59 05" src="https://cloud.githubusercontent.com/assets/1010210/18253082/ea1b006a-7389-11e6-9b7a-39b6e6f3efbd.png">

**Comment by andmarios** [comment]
Thanks for the report! I can't reproduce the issue though. We fixed a same problem about two weeks ago, so could it be that you don't have the latest image? You can try to pull the latest version:

```
docker pull landoop/kafka-topics-ui:latest
```

Also try a hard refresh (CTRL+F5) because browsers sometimes cache locally our angular app.

**Comment by apetheriotis** [comment]
It seems I didn't have the latest image :/ Sorry for that.
Thanks for that Marios 👍
