### ISSUE TITLE
timeout setting should be configurable within docker

### ISSUE THREAD

**Issue by fuyar** [Landoop/kafka-topics-ui#74]
Hey guys,

I recently switch over the latest version : 0.9.2 that use v2 API of kafka-rest.

It seems like v2 api (with the new consumer thingy) is really slow for the first fetch of any consumer when dealing with pretty large topics.

I had "Empty Topic" shown over kafka-topic-ui for any large topic because it was hitting the timeout.

I changed the timeout on Kafka-rest but I also need to change the timeout specified by the ui when calling kafka-rest (/records).

Thanks !

**Comment by Antwnis** [comment]
Also `MAX_BYTES: "50000"` is set to default to 50Kbytes

If any of your topics contains msg > 50KByte you will need to tweak the above parameter as well

We've set the default time-out to 5sec - but most of the times we operate it at 1,5sec
We'll expose those parameters on the docker as well

**Comment by fuyar** [comment]
MAX_BYTES is ok in my case. I dont really understand why they added (in kafka-rest) max_bytes instead of max_rows. Doesnt make sense to me !

**Comment by andmarios** [comment]
Thanks for the feedback, greatly appreciated. Indeed, we should add this option.
I'll take care of it in the next days.

**Comment by andmarios** [comment]
Hello, it took a bit longer than it should but it was a busy week.
I added options for RECORD_POLL_TIMEOUT, as well as for MAX_BYTES and DEBUG_LOGS_ENABLE.

This addition is only available in the docker image `landoop/kafka-topics-ui:latest` which includes Kafka Topics UI 0.9.2.
```
docker run --rm -p 8000:8000 \
    -e "KAFKA_REST_PROXY_URL=http://kafka-rest:8082" \
    -e MAX_BYTES=100000 \
    -e RECORD_POLL_TIMEOUT=5000 \
    -e DEBUG_LOGS_ENABLED=false \
    landoop/kafka-topics-ui:latest
```

Hope this solves your issue!
