### ISSUE TITLE
Chinese characters cannot be displayed properly

### ISSUE THREAD

**Issue by zhangxudongsteven** [Landoop/kafka-topics-ui#75]
Hi,
    we have used this tool for a while, really helps a lot. But somehow, the Chinese characters can't be displayed properly, which shown as followed:
{\"des\":\"åºé¨é®é®æºè½æ¨é\",\"title\":\"G1895 15:37åè½¦\",\"ticker\":[\"14è½¦10Cå·ã10Då·\"]}
    Is there any configuration I can do to fix this problem?

Thanks
BR

**Comment by Antwnis** [comment]
Hi @zhangxudongsteven 

Did not manage to look into this ticket. How did you resolve this ?
