### ISSUE TITLE
Error when start kafka-topics-ui container: Interrupted system call

### ISSUE THREAD

**Issue by akking** [Landoop/kafka-topics-ui#77]
I had non-deterministic result when starting the kafka-topics-ui container. From the log it says:
```
Enabling proxy.
/run.sh: line 20: can't create /caddy/Caddyfile: Interrupted system call
Kafka REST Proxy URL to /api/kafka-rest-proxy.
```
Restarts the container may solve the problem but was wondering if there's a better way to do.

Context: 
- Docker-compose file: https://github.com/akking/community-catalog/blob/master/templates/kafka/0/docker-compose.yml
- Running on Rancher.

**Comment by andmarios** [comment]
Hello, thanks for the report.

Your docker-compose file looks fine. I think that both the line and the error message point to a docker issue.

The problematic line is pretty much standard bash: https://github.com/Landoop/kafka-topics-ui/blob/master/docker/run.sh#L16

The error message (interrupted system call) doesn't come from bash but from docker itself, probably from some of the standard go libraries docker is using.

I don't know if this is something rancher specific, if you use bash on windows (a quick search seems to return this as a possible culprit), or something else.

Could you share more about your setup, like your operating system and how you access rancher? Maybe I can do some tests.

**Comment by akking** [comment]
Thank you so much for your prompt response. We are running Rancher on Rancher OSs on a cluster of machines.  

I tried to narrow the problem by reproducing the problem but the error happens like randomly under same docker-compose file.

**Comment by andmarios** [comment]
I am afraid I can't help much because I can't reproduce the bug and I haven't any experience with RancherOS —nor the time to familiarize with it, unfortunately. :(

Looking a bit into rancher-compose (I guess this is what you use? ), there is a debug flag that may help you: 
http://docs.rancher.com/rancher/v1.6/en/cattle/rancher-compose/

**Comment by OneCricketeer** [comment]
Also seeing this on MacOS

```
docker run --rm -it -p 8082:8000  -e "KAFKA_REST_PROXY_URL=http://kafka-rest-proxy:8082"  -e "PROXY=true" landoop/kafka-topics-ui
Enabling proxy.
/run.sh: line 23: can't create /caddy/Caddyfile: Interrupted system call
Kafka REST Proxy URL to /api/kafka-rest-proxy.

Activating privacy features... done.
http://0.0.0.0:8000
```

**Comment by akking** [comment]
What's weird is that the error comes from line 23, at the `fi` block. If it can't create the file, why it doesn't happen at line 21 `EOF`? Why `cat` not closing the file at `EOF` line?

**Comment by akking** [comment]
What's weird is that the error comes from line 23, at the fi block. If it can't create the file, why it doesn't happen at line 21 EOF? Why cat not closing the file at EOF line?

Sorry, I didn't mean to close the issue. My mistake.

**Comment by Antwnis** [comment]
Is it possible that docker runs out of disk space?

**Comment by Arttii** [comment]
So the way of solving this, is to omit 
```
ADD Caddyfile /caddy/
```
, and instead write it out fully in the run.sh. I have no idea why this is happening, but thats' the only way I could get it to work.

I was facing this problem, when running this in Kubernetes on a Debian OS.

**Comment by andmarios** [comment]
Thanks @Arttii for following up on this. Indeed, this seems a complex issue and I never managed to reproduce it in order to debug. I will implement your workaround, thanks again!

**Comment by Overbryd** [comment]
I am facing the same problem here, running on a GCE based Kubernetes cluster.

```
kubectl -n kafka logs -f deploy/kafka-tools topics-ui
Enabling proxy.
/run.sh: line 53: can't create /caddy/Caddyfile: Interrupted system call
Kafka REST Proxy URL to /api/kafka-rest-proxy.

Activating privacy features... done.
http://0.0.0.0:8000
```

**Comment by andmarios** [comment]
I just pushed a possible fix with commit 762792a6edb0d65412719381b90bc36157cc5c5f.
Could you please pull the latest image (`docker pull landoop/kafka-topics-ui:latest`) and give it a try?

**Comment by Overbryd** [comment]
Seems to work just fine 👍 

```console
$ kubectl -n kafka logs kafka-tools-1648884374-7f3jf topics-ui
Enabling proxy.
Kafka REST Proxy URL to /api/kafka-rest-proxy.

Activating privacy features... done.
http://0.0.0.0:8000
```

**Comment by Antwnis** [comment]
Thats this helps a lot. We can apply the same fix on our other dockers as well, to make sure no such glitches come up 👍

**Comment by andmarios** [comment]
Thanks both @Arttii and @Overbryd and to all people who contributed on this issue. We couldn't have solved it without you!
