### ISSUE TITLE
Seek to end doesn't work

### ISSUE THREAD

**Issue by akking** [Landoop/kafka-topics-ui#78]
Hello, 

> Seek to end

always give me 

>No data fetched

any idea what cause the problem?

Thank you.

**Comment by Antwnis** [comment]
`Seek to end` means 
> Get the pointer AFTER the last message and poll for RECORD_POLL_TIMEOUT

So with the default configured values, every time you seek-to-the end, the UI will display records added on the topic in the 500 msec after you press the seek-to-end button.

Hope this helps

**Comment by akking** [comment]
Yes, that helps. Thank you. However, can I change this default config into something like
> Get the pointer of the last message and poll for that record?

Thank you

**Comment by Antwnis** [comment]
No unfortunately in Kafka `latest` means 
> AFTER THE LAST MESSAGE

To get the last message new backend APIs will need to be in place
It will eventually happen - but not right now :)

**Comment by akking** [comment]
Thank you so much. I assume you used this [API](http://docs.confluent.io/current/kafka-rest/docs/api.html#post--consumers-(string-group_name)-instances-(string-instance)-positions-end), right?

**Comment by Antwnis** [comment]
Yeap
