### ISSUE TITLE
topic ui cannot list the toppics

### ISSUE THREAD

**Issue by Cloud-Leung** [Landoop/kafka-topics-ui#79]
![1](https://user-images.githubusercontent.com/16982375/27018604-67deef5a-4f64-11e7-82c8-8c2de110da10.png)

![2](https://user-images.githubusercontent.com/16982375/27018632-88f0bbce-4f64-11e7-8727-02d10d423ee5.png)

toppic ui can see how many toppics ,but it didn't list them , so i can't fetch the topic content.
and i check the request in topic ui /api/kafka-rest-proxy/topics , it response "["_schemas","logs-platform_json","logs-platform_text","logs-tenant_json","logs-tenant_text","muti-partion","text-log-v1"]".
this is my topic ,i think my rest maybe correct .

and my topic ui version is 0.8.3 ,i use this docker  image: landoop/kafka-topics-ui:0.8.3.
because i met the same problem justlike #72  , could you help me ?

**Comment by ssiahetiong** [comment]
Try clearing your cache or open this url in a different tab, then ctrl+f5:
http://_____/src/kafka-topics/list/topics-list.html

**Comment by Cloud-Leung** [comment]
thanks ！ it does work！
