### ISSUE TITLE
getting kafka-topics-ui running against a kafka set-up alternative to the bundled confluent one

### ISSUE THREAD

**Issue by Analect** [Landoop/kafka-topics-ui#8]
@andmarios 
You were able to help me last week over [here](https://github.com/Landoop/fast-data-dev/issues/2) on the fast-data-dev by allowing me to add `ADV_HOST` to the kafka ... I was just wondering if you might be able to point me in the right direction here.

I was running through this [debezium tutorial](http://debezium.io/docs/tutorial/), which ends with various running containers. 

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
90ca0b0f7284        debezium/connect:0.3                    "/docker-entrypoint.s"   2 hours ago         Up 2 hours          0.0.0.0:8083->8083/tcp, 9092/tcp                                         connect
3308ef37f780        debezium/kafka:0.3                      "/docker-entrypoint.s"   2 hours ago         Up 2 hours          9092/tcp                                                                 watcher
40feb981ad0d        mysql:5.7                               "docker-entrypoint.sh"   3 hours ago         Up 3 hours          3306/tcp                                                                 mysqlterm
bc4bddc80856        debezium/example-mysql:0.3              "docker-entrypoint.sh"   3 hours ago         Up 3 hours          0.0.0.0:3306->3306/tcp                                                   mysql
8023332452db        debezium/kafka:0.3                      "/docker-entrypoint.s"   3 hours ago         Up 3 hours          0.0.0.0:9092->9092/tcp                                                   kafka
d9e4ccd6e3d8        debezium/zookeeper:0.3                  "/docker-entrypoint.s"   3 hours ago         Up 3 hours          0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp   zookeeper
```

I wanted to be able to bolt on the 'kafka-topics-ui', so that I could get a better visual inspection of what was going on.  For that, I know I needed to add kafka-rest and schema-registry into the mix, so I followed the approach documented [here](https://github.com/confluentinc/cp-docker-images/blob/master/docs/quickstart.rst).

Unlike in that quickstart, I tried adding --net=host and exposing the ports, as per the following commands.

`docker run -d --net=host -p 8082:8082 --name=kafka-rest -e KAFKA_REST_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_REST_LISTENERS=http://localhost:8082 -e KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081 confluentinc/cp-kafka-rest:3.0.1`

`docker run -d --net=host -p 8081:8081 --name=schema-registry -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:2181 -e SCHEMA_REGISTRY_HOST_NAME=localhost -e SCHEMA_REGISTRY_LISTENERS=http://localhost:8081 confluentinc/cp-schema-registry:3.0.1`

However, for reasons I'm not fully clear about, these ports don't show up as exposed, which is possibly one of the reasons why kafka-topics-ui is failing.

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
d8a0b1dbbb26        confluentinc/cp-kafka-rest:3.0.1        "/etc/confluent/docke"   16 minutes ago      Up 16 minutes                                                                                kafka-rest
3869e740d5d3        confluentinc/cp-schema-registry:3.0.1   "/etc/confluent/docke"   17 minutes ago      Up 17 minutes                                                                                schema-registry
```

Here's the screenshot of the kafka-topics-ui ... where it obviously isn't able to connect properly to the kafka-rest.  Is there anything obvious to you that I might be missing here.  Is it even possible to mix the debezium containers with the confluent ones ... I was under the impression that the debezium ones are ultimately derived from the confluent ones too.

![image](https://cloud.githubusercontent.com/assets/4063815/18579202/1fc2ec2c-7bec-11e6-94a7-41a3696d69ac.png)

Thanks for any advice you might have.
Colum

**Comment by andmarios** [comment]
Hello! The ports don't show as exposed because you use `--net=host`. This means that the container runs on the host's network, so every port is already on the host.

_kafka-topics-ui_ probably doesn't work due to _localhost_. Kafka-topics-ui is a javascript app and runs in your browser. Your browser tries to connect to `localhost:8081` which of course for it is your computer instead of your server.

A quick thing to try, is to run the docker image like this:

```
docker run --rm -it -p 8000:8000 \
       -e "KAFKA_REST_PROXY_URL=http://<YOUR_SERVER_IP>:8081" \
       landoop/kafka-topics-ui
```

If the REST Proxy service has proper CORS settings, it should work.

If it doesn't work, drop us a line and we may think of something.

**Comment by Analect** [comment]
Thanks for the guidance @andmarios 
I tried various things (see kafka-rest command lower down) ... including adding `-e ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*"` to the run script for kafka-rest (as per [here](https://github.com/apache/kafka/commit/eb823281a52f3b27c3a889e7412bc07b3024e688)  ... and played around with exposing port 8082, linking the zookeeper container and removing the `--net=host` ... however, I could only get a response from `curl http://localhost:8082` on the server running all these containers when using the `--net=host` and wasn't able to get any response from curling from an external machine.

I don't really know enough about CORS to solve this!

`docker run -d -p 8082:8082 --name=kafka-rest --link zookeeper --link schema-registry -e ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*" -e KAFKA_REST_ZOOKEEPER_CONNECT=zookeeper:2181 -e KAFKA_REST_LISTENERS=http://localhost:8082 -e KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081 confluentinc/cp-kafka-rest:3.0.1`

**Comment by andmarios** [comment]
So, did running the image with `-e "KAFKA_REST_PROXY_URL=http://<YOUR_SERVER_IP>:8081"` helped you at least connect to the REST proxy?

We have in mind to add an option to the docker image to proxy the schema registry and REST proxy, which would make things easier but I haven't implemented it yet.

**Comment by andmarios** [comment]
I just pushed a new build with the proxy feature. Now the container can serve as a proxy between the Kafka REST and the client.

You could try something like:

```
docker run --rm -it --net=host \
           -e "KAFKA_REST_PROXY_URL=http://localhost:8081" \
           -e "PROXY=true" \
           landoop/kafka-topics-ui
```

This should work now as the localhost:8081 address will be used by the container and not your
browser.

**Comment by Analect** [comment]
@andmarios 
Thanks for helping me work this out.  It's much appreciated.  I haven't got it working yet .. since I think I need to re-adjust how I'm starting the kafka-rest and schema-registry containers .. in terms of reverting back to --net=host rather than exposing the ports with the `-p` flag  ... but just wanted to check something first.  You have KAFKA_REST_PROXY_URL set to port 8081 above ... should it not be 8082 .. which kafka-rest typically uses?  And is the SCHEMAREGISTRY_UI_URL environment variable required, as per my command below?

I'm trying this ... 
`docker run --rm -it --net=host -e "PROXY=true" -e "KAFKA_REST_PROXY_URL=http://localhost:8082" -e "SCHEMAREGISTRY_UI_URL=http://localhost:8081" landoop/kafka-topics-ui`

```
Enabling proxy.
Setting Schema Registry UI URL to http://localhost:8081.
Kafka REST Proxy URL to /api/kafka-rest-proxy.
Activating privacy features... done.
http://0.0.0.0:8000
```

Still not getting connection ... but will try adjust kafka-rest and schema-registry containers ... as mentioned above.

![image](https://cloud.githubusercontent.com/assets/4063815/18579335/fd95b07a-7bec-11e6-8ed2-5dbe9674fae1.png)

**Comment by Analect** [comment]
@andmarios 
Progress!

I ran up the kafka-rest container like this:
`docker run -d --net=host --name=kafka-rest -e ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT="*" -e KAFKA_REST_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_REST_LISTENERS=http://localhost:8082 -e KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081 confluentinc/cp-kafka-rest:3.0.1`

and the kafka-topics-ui like this:
`docker run --rm -it --net=host -e "PROXY=true" -e "KAFKA_REST_PROXY_URL=http://localhost:8082" -e "SCHEMAREGISTRY_UI_URL=http://localhost:8081" landoop/kafka-topics-ui`

and I can now at least see the topics.
![image](https://cloud.githubusercontent.com/assets/4063815/18579842/01808fa4-7bf0-11e6-8a3e-e781113e5275.png)

However, I'm having the same problem as was the case over on the fast-data-dev repo, where the UI isn't understanding the message content.

Here are the console logs from chrome:
https://gist.github.com/Analect/fc673ece858a069ccbe2736da4f6b44c

As mentioned further up this thread ... I have been following [this](http://debezium.io/docs/tutorial/) tutorial, which appears to use a standard 'avro' protocol ... so I'm not sure why the kafka-topics-ui is having trouble reading this ... or perhaps there's something else that is causing a problem.

**Comment by Analect** [comment]
It does say in that tutorial:

> The JSON converter does produce very verbose events since it includes the key and value schemas in every message. The Avro converter, on the other hand, is far smarter and results in far smaller event messages. The Avro converter transforms each Kafka Connect schema into an Avro schema and stores the Avro schemas in a separate Schema Registry service. Thus when the Avro converter serializes an event message, it places only an unique identifier for the schema along with an Avro-encoded binary representation of the value. Thus, the serialized messages transferred over the wire and stored in Kafka are far smaller than they appear above. In fact, the Avro Converter is able to use Avro schema evolution techniques to maintain the history of each schema in the Schema Registry.

That may be the source of  our problem .. it seems to suggest that messages are passed through an Avro-converter ... and stored in 'Avro-encoded binary' form.

**Comment by Antwnis** [comment]
@Analect if you want to follow the best-practices and utilize the `schema-registry` then when
- producing messages or
- reading messages from kafka

you should be using the serializers that support the schema-registry (lines 54+55 bellow) 

https://github.com/Landoop/landoop-avro-generator/blob/master/src/main/java/com.landoop.avrogenerator/AvroProducer.java#L54

This ensures that no JUNK messages will ever be posted on a topic - and that schemas are always properly register - and schema evolution rules are validated 

Once you do that - everything should work

**Comment by Analect** [comment]
@Antwnis 
Thanks for your input.

As someone somewhat out of their depth with this stuff (referring to me, of course!) ... presumably this usage of `KafkaAvroSerializer` mentioned above would need to happen within the debezium code ... specifically this [mysql-connector](https://github.com/debezium/debezium/tree/master/debezium-connector-mysql) tool.

As per the blurb from their tutorial that I reproduced above ... is it likely that their usage of [`io.confluent.connect.avro.AvroConverter`](https://github.com/debezium/debezium/blob/4de56fd657b243bae143decab29452c8a31c8015/debezium-core/src/test/java/io/debezium/data/VerifyRecord.java) and [`io.debezium.util.AvroValidator`](https://github.com/debezium/debezium/blob/330a27ce5201bd286e6ff8b16f17851efd5cc5c5/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java) (as per the links below) should already produce `avro` that kafka-topics-ui should be able to understand?

It's probably not realistic for me to modify how their messages are getting manifested in kafka ... I had just hoped that 'kafka-topics-ui' might have aided in understanding the way their connector works.

**Comment by andmarios** [comment]
Glad it worked! Though you shouldn't need to set any CORS with the proxy option.

@Analect , can I ask you why you test so many docker images? We are really interested on how people use kafka and their pain points.
Do you plan to run a dockerized confluent environment on production? Was there something missing from the docker images you tried?

**Comment by Analect** [comment]
@andmarios 

> can I ask you why you test so many docker images? We are really interested on how people use kafka and their pain points.

To be honest, I hadn't previously had time to dive into the whole suite of confluent solutions ... Kafka Connect, Schema Registry etc... and so, I was mainly operating with just a plain wurstmeister/kafka set-up, where I was interacting directly with kafka with consumers/producers written in [node](https://github.com/SOHU-Co/kafka-node) and [python](https://github.com/Parsely/pykafka), although some of these are struggling to keep up with the pace of kafka's new features.

I stumbled upon the landoop/kafka-topics-ui ... when I went looking for a better GUI to visualise topics and messages within kafka.  Separately, I also wanted to experiment with some of the change-data-capture solutions involving kafka out there, which led me to debezium, who have (or at least will soon have) three connectors I'm interested in ... mysql, postgres and mongodb ..

So, yes, it seems like I'm experimenting with anything and everything .. but more out a need to inform myself!  Having kafka-topics-ui work with some of these set-ups that differ slightly from the landoop ones is helpful to have ... so your efforts to nudge me forward on this front are greatly appreciated.

But certain hurdles ... like not being able to fix why certain message types aren't able to get rendered in your UI isn't something I have enough expertise to trouble-shoot.

**Comment by andmarios** [comment]
Thanks for the elaborate answer!

Btw, we think to add to _fast-data-dev_ a preview build of Confluent's new JDBC connector which supports any JDBC compatible database as sink or source—MySQL and Postgres in your case. We took part in its development and are eager to get it out there, but it needs some testing on our part before we add it.

**Comment by Analect** [comment]
I'd be interested in experimenting with it, if that were an option.  If there were a way to include their https://github.com/confluentinc/kafka-connect-elasticsearch ... as a sink, that would be very helpful too.  

I'm assuming that it would be a straight-forward JDBC connector that ingests table(s) or view(s) from the RDBMS rather than anything that tries to hook into the binlog or WAL and capture the changes ... as per the debezium solution?

**Comment by andmarios** [comment]
If I understand correctly, you need a connector source for JDBC and a connector sink for ElasticSearch?

If that's the case, _fast-data-dev_ already has everything you need. Confluent comes by default with a JDBC source (the sink is the new part we want to give a preview for) and we also include [Datamountaineer's connectors](https://github.com/datamountaineer/stream-reactor) which include an ElasticSearch sink.

Have a look at the links below:
- http://docs.confluent.io/3.0.1/connect/connect-jdbc/docs/index.html
- http://docs.datamountaineer.com/en/latest/elastic.html

We do plan to include other connectors in the future or provide builds for them. If you give fast-data-dev a spin again, remember to pull the latest.

**Comment by Analect** [comment]
@andmarios ... thanks for the above details.  I'm going to explore that today. 

Separately, could I trouble you once more (or maybe I need to ask Antwnis).  I didn't think this warranted me creating a separate issue on the schema-registry-ui repo, but I can if you prefer.

I know that the fast-data-dev repo bundles both 'ui' components, but I'm trying to get them running with this alternative kafka setup (https://gist.github.com/Analect/678d05dcf5ddbe123091e2f159827839), with each containerized (if at all possible), as a learning exercise to see how I can possibly use the schema-registry-ui to add a schema that allows me to set up avro messaging for [this](http://debezium.io/docs/tutorial/) tutorial, against the default JSON one, a process which is partly outlined [here](http://debezium.io/blog/2016/09/19/Serializing-Debezium-events-with-Avro/) .. but where there are still lots of gaps in my knowledge in terms of how all this works!

The compose file I link to above works fine until I add the `schema-registry-ui` at the bottom, which then conflicts with the `kafka-topics-ui` ... as both bind to port 8000.  I tried adding a ports "8001:8000" setting for the schema-registry-ui ... but that doesn't resolve, since we're using network_mode=host (the only way I was able to get this working in compose) ... so they are both trying to use the host port 8000.

```
       Name                    Command             State                                    Ports                                  
----------------------------------------------------------------------------------------------------------------------------------
connect              /docker-entrypoint.sh start   Up       0.0.0.0:8083->8083/tcp, 9092/tcp                                       
kafka                /docker-entrypoint.sh start   Up       0.0.0.0:9092->9092/tcp                                                 
kafka-rest           /etc/confluent/docker/run     Up                                                                              
kafka-topics-ui      /run.sh                       Up                                                                              
schema-registry      /etc/confluent/docker/run     Up                                                                              
schema-registry-ui   /run.sh                       Exit 1                                                                          
zookeeper            /docker-entrypoint.sh start   Up       0.0.0.0:2181->2181/tcp, 0.0.0.0:2888->2888/tcp, 0.0.0.0:3888->3888/tcp 
# docker-compose logs schema-registry-ui
Attaching to schema-registry-ui
schema-registry-ui    | Enabling proxy.
schema-registry-ui    | Setting Schema Registry URL to /api/schema-registry.
schema-registry-ui    | Activating privacy features... done.
schema-registry-ui    | 2016/09/21 10:57:43 listen tcp :8000: bind: address already in use
```

Can you suggest how I might get this to work?

On a related matter, from the kafka-topics-ui, I can see a reference to the schema registry (A below) ... but obviously when clicking on B, it just takes me to a 'localhost:8081'.  I'm not sure if there's a way to use a proxy to trick it the way you resolved the kafka-rest-proxy last week.

![image](https://cloud.githubusercontent.com/assets/4063815/18709077/1df86bfc-7ff6-11e6-86f9-2a1d36f70405.png)

**Comment by andmarios** [comment]
Depending on your docker setting, you may be able to access the host (your server) from inside your container.
Run `ifconfig eth0` on your server and find its IP. Then configure our docker images like this, replacing the server's IP:

```
  kafka-topics-ui: 
    image: landoop/kafka-topics-ui
    container_name: kafka-topics-ui
    environment: 
      PROXY: "true"
      KAFKA_REST_PROXY_URL: http://<IP>:8082
      SCHEMAREGISTRY_UI_URL: http://<IP>:8081
    ports:
      - 8001:8000
```

**Comment by Analect** [comment]
Unfortunately that didn't fix.  Played around with a number of different settings.
Commenting out `network_mode: host` on the kafka-topics-ui and adding the `ports: - 8001:8000` allows me to bring up both UIs (one on port 8000, the other on port 8001), the kafka-topics-ui breaks though ... in terms of being not able to connect with the REST API, with a 502 Gateway error ... tried commenting out `PROXY:true` on kafka-topics-ui ... and interchanging localhost:8082 with my-server-ip:8082 ... 

This is what the end part of the docker-compose looks like.  I've kept schema-registry-ui in here, since I don't think that is rolled into kafka-topics-ui, is it?

```
  kafka-topics-ui: 
    image: landoop/kafka-topics-ui
    container_name: kafka-topics-ui
    environment: 
      PROXY: "true"
      KAFKA_REST_PROXY_URL: http://<my-server-ip>:8082
      SCHEMAREGISTRY_UI_URL: http://<my-server-ip>:8081
    ports:
      - "8001:8000"
#    network_mode: "host"
  schema-registry-ui: 
    image: landoop/schema-registry-ui
    container_name: schema-registry-ui
    environment: 
      PROXY: "true"
      SCHEMAREGISTRY_URL: http://localhost:8081
    network_mode: "host"
```

This is what I was getting in the browser console:

```
POST http://<my-server-ip>:8001/api/kafka-rest-proxy/consumers/Consumer-1474466258971-json 502 (Bad Gateway)(anonymous function) @ angular.js:12011n @ angular.js:11776(anonymous function) @ angular.js:11571(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:1761invoke @ angular.js:4718c @ angular.js:1759Bc @ angular.js:1779fe @ angular.js:1664(anonymous function) @ angular.js:31763b @ angular.js:3207Sf @ angular.js:3497d @ angular.js:3485
angular.js:13920undefined
angular.js:12011GET http://<my-server-ip>:8001/api/kafka-rest-proxy/brokers 502 (Bad Gateway)(anonymous function) @ angular.js:12011n @ angular.js:11776(anonymous function) @ angular.js:11571(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:1761invoke @ angular.js:4718c @ angular.js:1759Bc @ angular.js:1779fe @ angular.js:1664(anonymous function) @ angular.js:31763b @ angular.js:3207Sf @ angular.js:3497d @ angular.js:3485
angular.js:12011GET http://<my-server-ip>:8001/api/kafka-rest-proxy/topics 502 (Bad Gateway)(anonymous function) @ angular.js:12011n @ angular.js:11776(anonymous function) @ angular.js:11571(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790(anonymous function) @ angular.js:1761invoke @ angular.js:4718c @ angular.js:1759Bc @ angular.js:1779fe @ angular.js:1664(anonymous function) @ angular.js:31763b @ angular.js:3207Sf @ angular.js:3497d @ angular.js:3485
angular.js:13920Failure with : {"data":"502 Bad Gateway\n","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/kafka-rest-proxy/brokers","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Bad Gateway"}(anonymous function) @ angular.js:13920failure @ combined.js:1208(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790l @ angular.js:11831J @ angular.js:12033t.onload @ angular.js:11966
angular.js:13920Error in getting topics from kafka-rest : {"data":"502 Bad Gateway\n","status":502,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/kafka-rest-proxy/topics","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"Bad Gateway"}(anonymous function) @ angular.js:13920failure @ combined.js:835(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790l @ angular.js:11831J @ angular.js:12033t.onload @ angular.js:11966
angular.js:13920Failed: Error in getting topics from kafka-rest(anonymous function) @ angular.js:13920(anonymous function) @ combined.js:1657(anonymous function) @ angular.js:16383$eval @ angular.js:17682$digest @ angular.js:17495$apply @ angular.js:17790l @ angular.js:11831J @ angular.js:12033t.onload @ angular.js:11966
angular.js:13920Starting kafka-topics controller : home
```

**Comment by andmarios** [comment]
Did you use `ifconfig` to find the IP? If you are on AWS or GCE, your server's real IP is different from the external one they assign you.

Another solution is to build your own version of one of our containers. It is super easy:

```
git clone https://github.com/Landoop/kafka-topics-ui.git
cd kafka-topics-ui/docker
emacs Caddyfile # Set a different port
docker build -t analect/kafka-topics-ui .
```

**Comment by Analect** [comment]
I'm running on a digital ocean droplet, where the 'real' IP is the same as the external one ... I think, at least.  So I had been using the right one ... in fact, I ended up arriving at the same approach you suggest above .. I built a new schema-registry-ui image ... changing the port in the Caddyfile to 8001 and also changing the EXPOSE port in the Dockerfile to the same ... which appears to work OK.  It seems the documentation around setting up schemas is a bit sparse ... even looking at the confluent docs ... I'm slowly piecing things together ... slow being the operative word ... but thanks again for your assistance.

On the fast-data-dev, it seems the elastic connector points to a version 2.2 of elastic ... do you know if this will work against a 5.x version of ES (ie. the one currently in beta)? ... also, as per the screenshot below ... is that reference to 'cassandra' in the elastic connector docs a possible typo?

![image](https://cloud.githubusercontent.com/assets/4063815/18719346/f5cc6330-801e-11e6-89d1-6ae4ce21781d.png)

**Comment by andmarios** [comment]
Hmm, I haven't ran many tests with elasticsearch so I am not sure.

As for _cassandra_ I think it is a typo and should be corrected to `connect.elastic.export.route.query`.
