### ISSUE TITLE
Unable to load data within topics

### ISSUE THREAD

**Issue by Stephan3555** [Landoop/kafka-topics-ui#86]
Hello guys,

I have currently the following issue. We are using topics-viewer 0.9.2 but we cannot see the data within the topics anymore. The Chrome developer console lists following error:

![image](https://user-images.githubusercontent.com/2537072/31076215-6d067a08-a779-11e7-8dbd-56e7a68ccb23.png)

If I downgrade to 0.8.3 the data within the topics are shown in Chrome but not the topics anymore. In Microsoft Edge everything is fine for 0.8.3 (topics and data are shown).

Chrome version: 61.0.3163.100
Edge version: 40.15063.0.0

Kafka-Rest-Properties:

![image](https://user-images.githubusercontent.com/2537072/31076340-eb0b8aba-a779-11e7-9d5b-2ce6a1c98cae.png)

Thanks for your help,
Stephan

**Comment by Antwnis** [comment]
@Stephan3555 try to set 

```
consumer.request.timeout.ms=30000
bootstrap.servers=PLAINTEXT://10.42.159.0:9092,.....
```

Also more information regarding the settings are on https://github.com/Landoop/kafka-topics-ui/issues/72

Let us know if it resolves your issue :)

**Comment by Stephan3555** [comment]
Hi Antwnis,

thanks for your fast reply.

I tried

![image](https://user-images.githubusercontent.com/2537072/31078448-80161c6c-a782-11e7-910b-b9968678477d.png)

as well as 

![image](https://user-images.githubusercontent.com/2537072/31078530-c91f9294-a782-11e7-828c-9b3e8da734ad.png)

But unfortunately both tries ends up with the same errormessage in the Chrome developer console specified in my first post.

**Comment by Stephan3555** [comment]
Just saw that you suggested to change the consumer.request.timeout.ms as well.

Tested this again but unfortunately with the same result like above.

![image](https://user-images.githubusercontent.com/2537072/31078839-fb75ae58-a783-11e7-8420-f1e3bd55c3c8.png)

**Comment by Stephan3555** [comment]
In addition I set the environment variables for the kafka-rest-proxy as stated in #72 :

KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://10.42.149.0:9092,PLAINTEXT://10.42.119.107:9092,PL
AINTEXT://10.42.171.9:9092

KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS=30000

With the same result:

![image](https://user-images.githubusercontent.com/2537072/31082290-ce4a45f0-a78e-11e7-9ff9-8e65b7fc7bb3.png)

**Comment by Antwnis** [comment]
I see in the logs @Stephan3555 `api/kafka-rest-proxy`

This is the link to the embedded proxy `caddy` that we use in the docker images. Are you using docker ? If not you would have to set up
```
 KAFKA_REST: "http://kafka-rest-hostname-or-ip:port"```

in `env.js` so that the UI points directly to Kafka-REST backend (and not to a proxy address)

**Comment by Stephan3555** [comment]
Yes, we are using Docker together with Rancher in our infrastructure

**Comment by Antwnis** [comment]
5 days ago we fixed on a commit an issue for Rancher + some times kubernetes.
Can you please make sure you do a 

    `docker pull landoop/kafka-topics-ui:latest`

and then use the `:latest` version ? We have not released over the past 5 days, and possibly this could resolve your issue

**Comment by Stephan3555** [comment]
Hi Antwnis,

unfortunately its the same behaviour with the latest image.

Its strange because with 0.8.3 and Microsoft Edge everything is fine. But as soon as i change to latest/0.9.2 and Chrome/Edge the error occurs.

**Comment by andmarios** [comment]
Maybe it is your Kafka REST version?
0.9.x versions of Topics UI require REST Proxy 3.2.x (Kafka 0.10.2.x) or better in order to work as they utilize the new, v2 api of Kafka REST.

Also could you try to increase the Kafka Topics UI timeout setting? The default may be too low for your use case. If you are on docker, try to add an environment variable to change from 2 to 10 seconds:

    RECORD_POLL_TIMEOUT=10000

If you use a non-docker installation, adjust the setting inside `env.js`.

**Comment by Stephan3555** [comment]
Hello guys,

we solved the issue.
We use the REST Proxy for the topics viewer and other applications to fetch data from topics. Therefore we set consumer.max.poll.recors and consumer.max.partition.fetch.bytes to very high values.

After removing both properties the topics viewer works again.  Seems like the topics viewer cannot handle too large amount of data at once.

Thanks for your help!

**Comment by andmarios** [comment]
Glad you solved it and thanks for coming back with the real issue. I'll try to replicate it on our test environment and maybe our web devs will be able to find a solution so you can use the same REST Proxy for both your applications and Topics UI.

We also develop a commercial offering, Lenses for Apache Kafka, which do not rely on Kafka REST and offer many more capabilities. We are a bit pre-occupied currently, preparing our initial release. :)
http://www.landoop.com/kafka-lenses/

**Comment by Arttii** [comment]
So we noticed something potentially hilarious with this issue. As long as the topic is quite small settings consumer.max.poll.records and consumer.max.partition.fetch.bytes to something not very large, allows you to see the contents of the topic. 

As soon as there are more records, it stops working and you have to redeploy with larger values for these properties, otherwise nothing is visible. I guess one could calculate a semi accurate estimation for this values for it to work for extended amounts of time and then hope really hard.

I don't know, this might be a potential REST proxy issue? Or most probably what is happening is not enough bytes getting returned, so the deserialization does not work.

**Comment by Antwnis** [comment]
Hi @Arttii it seems to be a rest-proxy issue. Based on your experience, what is the `RECORD_POLL_TIMEOUT` that works best ? 

As far as i can tell - there is a trade-off here. A larg poll time-out will give you more certainty that data will be returned, but then you would need to be more patient.. i.e. wait for 5 seconds, even if the topic is empty. A smaller time-out would make the UI more responsive at the cost of not fetching data some of the times ..

As Marios mentioned, with Lenses i.e. https://www.landoop.com/docs/lenses/lenses/features/latest/ we've managed to overcome all those issues, and it takes ~200 msec to retrieve records even on topics that has (B)illion of messages

**Comment by rhaarm** [comment]
Why is RECORD_POLL_TIMEOUT not documented on the ReadMe? The documentation only shows that PROXY & KAFKA_REST_PROXY_URL are the only environment variables to adjust for the docker run.sh

**Comment by stheppi** [comment]
@rhaarm We appreciate you using our product. Fancy doing a PR so the documentation makes it clear?

**Comment by andmarios** [comment]
Hi @rhaarm . Actually all extra options (`PROXY_SKIP_VERIFY`, `MAX_BYTES`, `RECORD_POLL_TIMEOUT`, `DEBUG_LOGS_ENABLED`) are documented into the README as you can see:

- https://github.com/Landoop/kafka-topics-ui/tree/master/docker
- https://hub.docker.com/r/landoop/kafka-topics-ui/

**Comment by rhaarm** [comment]
Wow, I've scanned that so many times, I'm not sure how I overlooked it.
Sorry for jumping the gun. Maybe it one of the other UI components docker
that I was frustrated about.

**Comment by andmarios** [comment]
No worries! We all've been there!
