### ISSUE TITLE
nginx proxy error 404

### ISSUE THREAD

**Issue by scne** [Landoop/kafka-topics-ui#87]
I've a nginx proxy and I use this code below to forward request from external request.
**kafka-rest-proxy** was reachable without any problem, but **kafka-topics-ui** give me 404 every time.

Error page 404 isn't 404 error page by nginx but 404 error page by kafka-topics-ui

Any suggestions?

```
.....
location /kafka-rest-proxy {
      auth_basic "Restricted";
      auth_basic_user_file /etc/nginx/.htpasswd;
      rewrite /kafka-rest-proxy(.*) $1  break;
      proxy_set_header Host            $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_redirect off;

      proxy_pass http://ip:8082;

    }

    location /kafka-topics-ui {
      rewrite /kafka-topcis-ui(.*) $1  break;
      proxy_set_header Host            $host;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_ignore_client_abort on;
      proxy_pass http://ip:8000;
    }
```

**Comment by Antwnis** [comment]
How are you running kafka-topics-ui ?

 * Using the source ? (Did you build it and use the /dist/* folder)
 * From a release ? Which one ? https://github.com/Landoop/kafka-topics-ui/releases
 * From a docker ? https://hub.docker.com/r/landoop/kafka-topics-ui/

**Comment by scne** [comment]
Hi @Antwnis,

I'm using kafka-topics-ui in docker, to be honest I've all elk stack in running with docker and I've a proxy to forward request from external between ports.

Above I write part of my nginx proxy conf. I can't understand reason why kafka-rest-proxy works fine, instead kafka-topics-ui get me every time 404 error page.

**Comment by fox-md** [comment]
While rewriting make sure you don`t have typos in config like kafka-**topics**-ui kafka-**topcis**-ui
```
location /kafka-topics-ui {
      rewrite /kafka-topcis-ui(.*) $1  break;
```
