### ISSUE TITLE
Kafka Topics UI doesn't load partitions of a topic

### ISSUE THREAD

**Issue by drobati** [Landoop/kafka-topics-ui#92]
I can see all the topics, I just can't query the topics.

I use `docker-compose` with the network `dockerimages_default`.

The `docker-compose` spins up `debezium/zookeeper:latest`, `debezium/kafka:latest`, `confluentinc/cp-kafka-rest:latest`, `confluentinc/cp-schema-registry:latest`, and a custom debezium image for kafka connect that adds Avro support.

#### rest configuration
```
  rest:
    image: confluentinc/cp-kafka-rest:latest
    hostname: rest
    depends_on:
      - zookeeper
    ports:
      - '8082:8082'
    environment:
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_ID: 'kafka-rest-server'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema_registry:8081'
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAKFA_REST_DEBUG: 'true'
      KAFKA_REST_HOST_NAME: 'rest'
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
```

#### kafka-topics-ui command used
```
docker run --rm -it\
    -p 8001:8000 \
    -e "KAFKA_REST_PROXY_URL=http://$(docker-machine ip confluent):8082" \
    -e "PROXY=true" \
    --network=dockerimages_default \
    landoop/kafka-topics-ui
```

It's not until I request a certain topic that this message starts to dump. It seems to be stuck in an infinite loop. It still processes other requests to the REST proxy, but after it's done it continues to dump this.

#### kafka-rest proxy logs
```
...
[2017-10-20 17:26:33,746] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-10-20 17:26:33,847] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-10-20 17:26:33,898] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-10-20 17:26:33,948] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2017-10-20 17:26:33,999] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
...
```

The Topics UI continues to display the loading bar and never shows the partitions and such.

**Comment by drobati** [comment]
I believe I'm using Confluent Kafka-Rest Proxy `3.3.0` and whatever the latest `landoop/kafka-topics-ui` version is.

**Comment by andmarios** [comment]
Please try to set some bootstrap servers for Kafka REST as well. Please notice that you have to include the protocol for Kafka REST to work (contrary to common kafka consumers and producers):

    KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://[BROKER_ADDRESS]:9092

**Comment by drobati** [comment]
@andmarios THANKS! That worked perfectly!

Why is it that it needs a bootstrap server if provided zookeeper?

**Comment by AgoloKarimTawfik** [comment]
I am running the same command above and added the mentioned variable, but the docker start logs shows that I am still using the default `KAFKA_REST_PROXY_URL`

Any ideas why is this?

**Comment by drobati** [comment]
I added the mentioned variable to my REST entry in the docker-compose.yml not the topics-ui container.

**Comment by drobati** [comment]
I may have misunderstood but it sounds like you added the variable to the command not the REST proxy.

**Comment by AgoloKarimTawfik** [comment]
`docker run --rm -it -p 8000:8000 \
               -e "KAFKA_REST_PROXY_URL=http://127.0.0.1:8082" \
               -e "KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://127.0.0.1:9092" \
               -e "KAFKA_REST=http://127.0.0.1:8082" \
               -e "PROXY=true" \
               landoop/kafka-topics-ui`

This is the command I used.

**Comment by Antwnis** [comment]
```KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://127.0.0.1:9092```

Is a setting to be applied to **Kafka-Rest** in order to enable the new consumer API and thus the v2 REST APIs that the latest version of **Kafka-Topics-UI**  then utilizes

**Comment by AgoloKarimTawfik** [comment]
I think I am missing thing here, I just use the docker pull command mentioned in the github README,
are there any other steps I need to do, I am not that good with docker, that's why, it seems I missed a thing, it seems obvious

**Comment by AgoloKarimTawfik** [comment]
Thanks, I managed to make it work without docker, I added the CORS fields under `kafka-rest.properies` file and everthing went fine.

**Comment by andmarios** [comment]
@drobati 
> Why is it that it needs a bootstrap server if provided zookeeper?

The newer Kafka REST versions use only the new producer and consumer. These in turn work with bootstrap servers instead of zookeeper.

**Comment by drobati** [comment]
@andmarios, Thanks for the explanation. Still learning as much as I can about Kafka. I wasn't aware that the newer versions of producer and consumers, didn't have a reliance on zookeeper.
