### ISSUE TITLE
Topic is empty

### ISSUE THREAD

**Issue by longwuyuan** [Landoop/kafka-topics-ui#97]
Hi,

![image](https://user-images.githubusercontent.com/5085914/33916366-58de9298-dfe3-11e7-84f8-251922723eae.png)

![image](https://user-images.githubusercontent.com/5085914/33916373-5f35d5e8-dfe3-11e7-96cb-9305a1c846e9.png)

![image](https://user-images.githubusercontent.com/5085914/33916580-88724238-dfe4-11e7-92de-14f88ba5ba97.png)

![image](https://user-images.githubusercontent.com/5085914/33916595-9200a2ae-dfe4-11e7-861a-0ec95406fab7.png)

I can provide more info as needed.

Just want toknow if this can work with big topics or only option left is lenses.

Thanks.

**Comment by jglambed** [comment]
Hello,
I can't be sure with the provided info, but most likely this is a timeout problem.
Try changing the `RECORD_POLL_TIMEOUT` in `env.js` file to a higher value and tell us if that helps.
Default is `5000` in ms

**Comment by longwuyuan** [comment]
@jglambed  Much gratitude. Default was 2000 and I prefixed a 1 to make it 12000 and voila, I got the listing of tons of pages full of messages. Much gratitude again as this is a big deal for us. Wish I could contribute and hope others with similar problem get benefit. Thanks a lot.

**Comment by longwuyuan** [comment]
Can I pass RECORD_POLL_TIMEOUT as a env var to the container ?

**Comment by Antwnis** [comment]
yeap - have a look at https://github.com/Landoop/kafka-topics-ui/tree/master/docker#configuration-options @longwuyuan

**Comment by longwuyuan** [comment]
Unsure how to thank you guys but this is a masterpiece. The env var worked and we are going into production with this now. Speaks volumes about the quality. Thnx again.
